---
title: "appendix functions for SMT Dental Pack"
---

```{r libraries, include=FALSE}
library(tidyverse)
library(DBI)
library(odbc)
library(gridExtra)

options(scipen = 999)
```

```{r pull scheduled data}
# extract scheduled data from NCDR
pull_scheduled_data <- function(UDAorUOA = "UDA"){
  
  con <- dbConnect(odbc::odbc(), "NCDR")
  
  if(UDAorUOA == "UDA"){
    sql <- "SELECT * FROM [NHSE_Sandbox_PrimaryCareNHSContracts].[Dental].[UDA_scheduled] WHERE annual_contracted_UDA > 100"
    sql_historical <- "SELECT * FROM [NHSE_Sandbox_PrimaryCareNHSContracts].[Dental].[UDA_scheduled_historical] WHERE annual_contracted_UDA > 100"
  } else if(UDAorUOA == "UOA"){
    sql <- "SELECT * FROM [NHSE_Sandbox_PrimaryCareNHSContracts].[Dental].[UOA_scheduled] WHERE annual_contracted_UOA > 0"
    sql_historical <- "SELECT * FROM [NHSE_Sandbox_PrimaryCareNHSContracts].[Dental].[UOA_scheduled_historical] WHERE annual_contracted_UOA > 0"
  }
  
  scheduled <- dbGetQuery(con, sql)
  scheduled_historical <- dbGetQuery(con, sql_historical)
  
  if(UDAorUOA == "UDA"){
    scheduled_historical <- scheduled_historical %>% 
      select(-year) %>% 
      select(data_month:UDA_delivered, general_FP17s, UDA_band_1:FP17s_band_other)
  } else if(UDAorUOA == "UOA"){
    scheduled_historical <- scheduled_historical %>% 
      select(-c(region_code, UOA_financial_value, monthly_net_payment_to_dental_contract, 
                YTD_UOA_delivered, YTD_percentage_of_UOA_delivered))
  }
  
  scheduled_data_append <- rbind(scheduled, scheduled_historical) %>% 
    rename(month = data_month)
  
  scheduled_data_append
}

UDA_scheduled_data_append <- pull_scheduled_data(UDAorUOA = "UDA")
UOA_scheduled_data_append <- pull_scheduled_data(UDAorUOA = "UOA")
```

```{r pull unfiltered calendar data}
# extract calendar data from NCDR
pull_unfiltered_calendar_data <- function(UDAorUOA = "UDA"){
  con <- dbConnect(odbc::odbc(), "NCDR")
  
  if(UDAorUOA == "UDA"){
    sql <- "SELECT * FROM [NHSE_Sandbox_PrimaryCareNHSContracts].[Dental].[Calendar_UDA_Activity] WHERE UDA_PERF_TARGET > 100"
  } else if(UDAorUOA == "UOA"){
    sql <- "SELECT * FROM [NHSE_Sandbox_PrimaryCareNHSContracts].[Dental].[Calendar_UOA_Activity] WHERE UOA_PERF_TAR > 0"
  }
  
  calendar <- dbGetQuery(con, sql)
  
  # pull contractual dataset
  contractual_dataset<-pull_contractual_dataset()%>%
    mutate(YEAR_MONTH = as.Date(YEAR_MONTH))%>% 
  group_by(YEAR_MONTH) %>% summarize(CONTRACT_NUMBER = unique(CONTRACT_NUMBER))
  
  calendar <- calendar %>% 
  mutate(CONTRACT_NUMBER = as.numeric(CONTRACT_NUMBER)) %>% 
  inner_join(contractual_dataset,by=c('YEAR_MONTH','CONTRACT_NUMBER')) %>% 
  rename(month = YEAR_MONTH, 
         contract_number = CONTRACT_NUMBER)
  
  calendar
}

UDA_calendar_data_append <- pull_unfiltered_calendar_data(UDAorUOA = "UDA")

names(UDA_calendar_data_append) <- base::tolower(names(UDA_calendar_data_append))

UDA_calendar_data_append <- UDA_calendar_data_append %>% 
  rename(annual_contracted_UDA = uda_perf_target, 
         UDA_delivered = uda_delivered,
         commissioner_ods_code_icb = commissioner_code, 
         name_or_company_name = provider_name,
         FP17s_band_1 = band_1_delivered, 
         FP17s_band_2 = band_2_delivered, 
         FP17s_band_2a = band_2a_delivered,
         FP17s_band_2b = band_2b_delivered, 
         FP17s_band_2c = band_2c_delivered, 
         FP17s_band_3 = band_3_delivered,
         FP17s_band_urgent = band_urgent_delivered, 
         FP17s_band_other = band_other_delivered,
         UDA_band_1 = uda_band_1_delivered, 
         UDA_band_2 = uda_band_2_delivered, 
         UDA_band_3 = uda_band_3_delivered,
         UDA_urgent = uda_band_urgent_delivered, 
         UDA_other = uda_band_other_delivered)

# extract list of contracts in calendar table to use later to filter scheduled data
UDA_calendar_contract_list <- unique(UDA_calendar_data_append$contract_number)

UDA_scheduled_contract_list <- unique(UDA_scheduled_data_append$contract_number)

# repeat for UOA
UOA_calendar_data_append <- pull_unfiltered_calendar_data(UDAorUOA = "UOA")

names(UOA_calendar_data_append) <- base::tolower(names(UOA_calendar_data_append))

UOA_calendar_data_append <- UOA_calendar_data_append %>% 
  rename(annual_contracted_UOA = uoa_perf_tar, 
         UOA_delivered = uoa_delivered,
         commissioner_ods_code_icb = commissioner_code, 
         name_or_company_name = provider_name)

UOA_calendar_contract_list <- unique(UOA_calendar_data_append$contract_number)

UOA_scheduled_contract_list <- unique(UOA_scheduled_data_append$contract_number)
```

```{r plot time series comparison}
plot_time_series_comparison <- function(UDAorUOA = "UDA"){
  
  if(UDAorUOA == "UDA"){
    scheduled_data <- UDA_scheduled_data_append
    calendar_data <- UDA_calendar_data_append
    scheduled_contract_list <- UDA_scheduled_contract_list
    calendar_contract_list <- UDA_calendar_contract_list
    ylab <- "UDAs delivered"
    caption = "Contracts included: GDS/PDS/PDS+ where Total contracted UDA>100"
    title <- "UDA delivered by month for contracts in both data sources"
    
    # group by month and calculate sum of UDA delivered for scheduled and calendar data
    scheduled_delivered <- scheduled_data %>% 
      filter(contract_number %in% calendar_contract_list & 
               month <= max(scheduled_data$month) & month >= min(calendar_data$month)) %>% 
      group_by(month) %>% 
      summarise(delivered = sum(UDA_delivered, na.rm = TRUE)) %>% 
      mutate(source = "Scheduled data")
    
    calendar_delivered <- calendar_data %>% 
      filter(month <= max(scheduled_data$month)) %>% 
      group_by(month) %>% 
      summarise(delivered = sum(UDA_delivered, na.rm = TRUE)) %>% 
      mutate(source = "Calendar data")
    
  } else if(UDAorUOA == "UOA"){
    scheduled_data <- UOA_scheduled_data_append
    calendar_data <- UOA_calendar_data_append
    scheduled_contract_list <- UOA_scheduled_contract_list
    calendar_contract_list <- UOA_calendar_contract_list 
    ylab <- "UOAs delivered"
    caption = "Contracts included: GDS/PDS/PDS+ where Total contracted UOA>0"
    title <- "UOA delivered by month for contracts in both data sources"

    # group by month and calculate sum of UOA delivered for scheduled and calendar data
    scheduled_delivered <- scheduled_data %>% 
      filter(contract_number %in% calendar_contract_list & 
               month <= max(scheduled_data$month) & month >= min(calendar_data$month)) %>% 
      group_by(month) %>% 
      summarise(delivered = sum(UOA_delivered, na.rm = TRUE)) %>% 
      mutate(source = "Scheduled data")
    
    calendar_delivered <- calendar_data %>% 
      filter(contract_number %in% scheduled_contract_list & month <= max(scheduled_data$month)) %>% 
      group_by(month) %>% 
      summarise(delivered = sum(UOA_delivered, na.rm = TRUE)) %>% 
      mutate(source = "Calendar data")
  }

  # combine to use in plot
  total_delivered <- rbind(calendar_delivered, scheduled_delivered)

  # plot chart
  p <- ggplot(total_delivered, 
              aes(x = month, 
                  y = delivered, 
                  colour = source)) + 
    geom_line(size = 1) + 
    theme_bw() + 
    expand_limits(y = 0) + 
    scale_x_date(date_breaks = "3 months",
                 date_labels = "%b-%y") +
    scale_y_continuous(label = scales::comma) + 
    theme(axis.text.x = element_text(angle = 90, vjust=-0.0001)) +
    labs(x = "Month", 
         y = ylab, 
         colour = "Data source", 
         caption = caption) + 
    ggtitle(title) + 
    scale_color_manual(values = c("#E69F00", "#56B4E9"))

  p
}
```

```{r time series comparison table}
table_time_series_comparison <- function(UDAorUOA = "UDA"){
  
  if(UDAorUOA == "UDA"){
    scheduled_data <- UDA_scheduled_data_append
    calendar_data <- UDA_calendar_data_append
    scheduled_contract_list <- UDA_scheduled_contract_list
    calendar_contract_list <- UDA_calendar_contract_list
    
    # group by month and calculate sum of UDA delivered for scheduled and calendar data
    scheduled_delivered <- scheduled_data %>% 
      filter(contract_number %in% calendar_contract_list & 
               month <= max(scheduled_data$month) & month >= min(calendar_data$month)) %>% 
      group_by(month) %>% 
      summarise(delivered = sum(UDA_delivered, na.rm = TRUE)) %>% 
      mutate(source = "Scheduled data")#
    
    calendar_delivered <- calendar_data %>% 
      filter(contract_number %in% scheduled_contract_list & month <= max(scheduled_data$month)) %>% 
      group_by(month) %>% 
      summarise(delivered = sum(UDA_delivered, na.rm = TRUE)) %>% 
      mutate(source = "Calendar data")
  
  } else if(UDAorUOA == "UOA"){
    scheduled_data <- UOA_scheduled_data_append
    calendar_data <- UOA_calendar_data_append
    scheduled_contract_list <- UOA_scheduled_contract_list
    calendar_contract_list <- UOA_calendar_contract_list 
    
    # group by month and calculate sum of UOA delivered for scheduled and calendar data
    scheduled_delivered <- scheduled_data %>% 
      filter(contract_number %in% calendar_contract_list & 
               month <= max(scheduled_data$month) & month >= min(calendar_data$month)) %>% 
      group_by(month) %>% 
      summarise(delivered = sum(UOA_delivered, na.rm = TRUE)) %>% 
      mutate(source = "Scheduled data")#
    
    calendar_delivered <- calendar_data %>% 
      filter(contract_number %in% scheduled_contract_list & month <= max(scheduled_data$month)) %>% 
      group_by(month) %>% 
      summarise(delivered = sum(UOA_delivered, na.rm = TRUE)) %>% 
      mutate(source = "Calendar data")
  }
  
  # combine to use in table
  total_delivered <- rbind(calendar_delivered, scheduled_delivered)

  # create table for latest full financial year
  comparison_table <- total_delivered %>% 
    filter(month >= as.Date(previous_fy_start) & month <= as.Date(previous_fy_end)) %>% 
    pivot_wider(names_from = source, values_from = delivered) %>% 
    arrange(month) %>% 
    mutate(month = as.character(month), 
           `Scheduled data` = prettyNum(round(`Scheduled data`, 0), big.mark = ","),
           `Calendar data` = prettyNum(round(`Calendar data`, 0), big.mark = ",")) %>% 
    rename(Month = month)
  
  # convert table into graphical object to use in slides
  table_to_print <- tableGrob(comparison_table, rows = NULL)

  table_to_print
}
```
