---
title: "produce clean data for plotting for SMT Dental Pack"
---


```{r UDA delivered/contracted}

get_delivery_data <- function(data = UDA_calendar_data,
                              UDAorUOA = "UDA",
                              all_regions_and_STPs = F,
                              contractor_level = F,
                              renameColumns = F){
  
  #show different levels of information in output data if specified
  if(all_regions_and_STPs == TRUE){
    
    data <- data %>%
      group_by(month, region_name, commissioner_name)
    
    
  }else if(contractor_level == TRUE){
    
    data <- data %>%
      group_by(month, contract_number, commissioner_name)
    
  }else{
    
    data <- data %>%
      group_by(month)
  }
  
  if(UDAorUOA == "UDA"){
  #group by month/ICB/Region (depends on the previous step) and calculate total no UDAs delivered and contracted UDA
  UDA_UOAs_delivered <- data %>%
    summarise(monthly_UDA_UOAs_BAND1_delivered = sum(UDA_band_1, na.rm = T),
              monthly_UDA_UOAs_BAND2_delivered = sum(UDA_band_2, na.rm = T),
              monthly_UDA_UOAs_BAND3_delivered = sum(UDA_band_3, na.rm = T),
              monthly_UDA_UOAs_BAND_OTHER_delivered = sum(UDA_other, na.rm = T),
              monthly_UDA_UOAs_BAND_URGENT_delivered = sum(UDA_urgent, na.rm = T),
              monthly_UDA_UOAs_delivered = sum(UDA_delivered, na.rm = T),
              annual_contracted_UDA_UOA = sum(annual_contracted_UDA, na.rm = T))
  
  #for PCOR and SOF table
  if(renameColumns){
    
    new_data <- UDA_UOAs_delivered %>%
      select(treatment_month = month,
             commissioner_name,
             region_name,
             monthly_UDA_BAND1_delivered,
             monthly_UDA_BAND2_delivered,
             monthly_UDA_BAND3_delivered,
             monthly_UDA_BAND_URGENT_delivered,
             monthly_UDA_BAND_OTHER_delivered,
             monthly_UDAs_delivered = monthly_UDA_UOAs_delivered,
             annual_contracted_UDAs = annual_contracted_UDA_UOA)
  }
  }else if(UDAorUOA == "UOA"){
    #group by month/ICB/Region (depends on the previous step) and calculate total no UOAs delivered and contracted UOA
    UDA_UOAs_delivered <- data %>% 
      summarise(monthly_UDA_UOAs_delivered = sum(UOA_delivered, na.rm = T),
                annual_contracted_UDA_UOA = sum(annual_contracted_UOA, na.rm = T))
  }
  
  new_data <- UDA_UOAs_delivered
  
}

```

```{r banded CoT data}
get_banded_COTs_data <- function(data = UDA_calendar_data_FD,
                                 level = "National",
                                 all_regions_and_STPs = FALSE){

  if(level == "National"){
    
    #group by month and sum UDAs delivered
    new_data <- data %>%
      group_by(month)
    
    }else{
      
      #group by month and sum UDAs delivered
      # start from 2020-04-01 as region/ICB information not available before then
      new_data <- data %>%
        group_by(month, region_name, commissioner_name) %>% 
        filter(month >= "2020-04-01")
      }

#calculate total no of FP17s in each band
new_data <- new_data %>%
  summarise(band1 = sum(FP17s_band_1, na.rm = T),
            band2 = sum(FP17s_band_2, na.rm = T),
            band2a = sum(FP17s_band_2a, na.rm = T),
            band2b = sum(FP17s_band_2b, na.rm = T),
            band2c = sum(FP17s_band_2c, na.rm = T),
            band3 = sum(FP17s_band_3, na.rm = T),
            other = sum(FP17s_band_other, na.rm = T),
            urgent = sum(FP17s_band_urgent, na.rm = T))
}
```

```{r npp-comparison-data}
get_npp_data <- function(level = level, 
                         region_STP_name = region_STP_name, 
                         all_regions_STPs = FALSE){
  
  # filter for new_patient_tariff_amount > 0 to only count contracts seeing patients under NPP
  monthly_delivered_post <- npp_data %>% 
    filter(month >= "2024-03-01" &
             new_patient_tariff_amount > 0) %>% 
    group_by(month, commissioner_code, commissioner_name, region_name) %>% 
    summarise(TotalNPP = sum(band1_adult_count, band1_child_count, band23_adult_count, band23_child_count, na.rm = TRUE)) %>% 
    rename(YEAR_MONTH = month)
  
  if(level == "National"){
  
    data_pre <- monthly_delivered_pre %>% 
      filter(REGION == "National") %>% 
      select(YEAR_MONTH, total, financial_year, GROUP)
  
    data_post <- monthly_delivered_post %>% 
      group_by(YEAR_MONTH) %>% 
      summarise(total = sum(TotalNPP, na.rm = TRUE)) %>% 
      mutate(financial_year = "2024/25", 
             GROUP = "Post NPP launch - paid (2024/25)")
  
    } else if(level == "Regional"){
      
      if(all_regions_STPs == TRUE){
        
        data_pre <- monthly_delivered_pre %>% 
          group_by(REGION, TREATMENT_MONTH, GROUP) %>% 
          summarise(total = sum(total)) %>% 
          mutate(financial_year = ifelse(TREATMENT_MONTH <= "202402",
                                          "2023/24", "2024/25"), 
                  YEAR_MONTH = as.Date(paste(substr(TREATMENT_MONTH, 1, 4), 
                                              substr(TREATMENT_MONTH, 5, 6), 
                                              "01", sep = "-")))
        
        data_post <- monthly_delivered_post %>% 
          group_by(region_name, YEAR_MONTH) %>% 
          summarise(total = sum(TotalNPP, na.rm = TRUE)) %>% 
          mutate(financial_year = "2024/25", 
                  GROUP = "Post NPP launch - paid (2024/25)") %>% 
          rename(REGION = region_name)
        
      } else if(all_regions_STPs == FALSE){
  
      data_pre <- monthly_delivered_pre %>% 
        filter(REGION == region_STP_name) %>% 
        group_by(REGION, TREATMENT_MONTH, GROUP) %>% 
        summarise(total = sum(total)) %>% 
        mutate(financial_year = ifelse(TREATMENT_MONTH <= "202402",
                                       "2023/24", "2024/25"), 
               YEAR_MONTH = as.Date(paste(substr(TREATMENT_MONTH, 1, 4), 
                                          substr(TREATMENT_MONTH, 5, 6), 
                                          "01", sep = "-")))
      
      data_post <- monthly_delivered_post %>% 
        filter(region_name == region_STP_name) %>% 
        group_by(region_name, YEAR_MONTH) %>% 
        summarise(total = sum(TotalNPP, na.rm = TRUE)) %>% 
        mutate(financial_year = "2024/25", 
               GROUP = "Post NPP launch - paid (2024/25)") %>% 
        rename(REGION = region_name)
        }
      } else if(level == "STP"){
        
        if(all_regions_STPs == TRUE){
          
          data_pre <- monthly_delivered_pre %>% 
            group_by(COMMISSIONER_NAME, TREATMENT_MONTH, GROUP) %>% 
            summarise(total = sum(total)) %>% 
            mutate(financial_year = ifelse(TREATMENT_MONTH <= "202402",
                                          "2023/24", "2024/25"), 
                    YEAR_MONTH = as.Date(paste(substr(TREATMENT_MONTH, 1, 4), 
                                          substr(TREATMENT_MONTH, 5, 6), 
                                          "01", sep = "-")))
          data_post <- monthly_delivered_post %>% 
            group_by(commissioner_name, YEAR_MONTH) %>% 
            summarise(total = sum(TotalNPP, na.rm = TRUE)) %>% 
            mutate(financial_year = "2024/25", 
                    GROUP = "Post NPP launch - paid (2024/25)")
        }
        
        if(all_regions_STPs == FALSE){
  
        data_pre <- monthly_delivered_pre %>% 
          filter(COMMISSIONER_NAME == region_STP_name) %>% 
          group_by(COMMISSIONER_NAME, TREATMENT_MONTH, GROUP) %>% 
          summarise(total = sum(total)) %>% 
          mutate(financial_year = ifelse(TREATMENT_MONTH <= "202402",
                                         "2023/24", "2024/25"), 
                 YEAR_MONTH = as.Date(paste(substr(TREATMENT_MONTH, 1, 4), 
                                      substr(TREATMENT_MONTH, 5, 6), 
                                      "01", sep = "-")))
  
        data_post <- monthly_delivered_post %>% 
          filter(commissioner_name == region_STP_name) %>% 
          group_by(commissioner_name, YEAR_MONTH) %>% 
          summarise(total = sum(TotalNPP, na.rm = TRUE)) %>% 
          mutate(financial_year = "2024/25", 
                 GROUP = "Post NPP launch - paid (2024/25)")
        }
      }
  
  data_combined <- rbind(data_pre, data_post) %>% 
          mutate(month_name = month.name[month(YEAR_MONTH)], 
                 month_name = factor(month_name, 
                                     levels = c("March", "April", "May", "June", "July", "August", 
                                                "September", "October", "November", "December", "January", "February")),
                 GROUP = factor(GROUP, 
                                levels = c("Pre NPP launch (2023/24)", "Post NPP launch - unpaid (2024/25)", "Post NPP launch - paid (2024/25)")))
  }
```