# create metadata table
metadata <- data.frame(Tab = c("Dental contract & activity", 
                               "Dental contract & activity",
                               "Dental contract & activity",
                               "Dental contract & activity",
                               "Dental contract & activity",
                               "Dental contract & activity",
                               "Dental contract & activity",
                               "Dental contract & activity",
                               "Dental contract & activity",
                               "Dental contract & activity",
                               "Dental contract & activity",
                               "Dental contract & activity",
                               "Dental contract & activity",
                               "Dental contract & activity",
                               "Dental contract & activity",
                               "Dental contract & activity",
                               "Dental contract & activity", 
                               "Dental contract & activity", 
                               "Dental contract & activity", 
                               "Dental contract & activity", 
                               "Dental contract & activity", 
                               "Dental contract & activity",
                               "Orthodontic contract & activity",
                               "Orthodontic contract & activity",
                               "Orthodontic contract & activity",
                               "Orthodontic contract & activity",
                               "Orthodontic contract & activity",
                               "Orthodontic contract & activity",
                               "Orthodontic contract & activity",
                               "Orthodontic contract & activity",
                               "DCP",
                               "DCP",
                               "DCP",
                               "DCP",
                               "DCP",
                               "DCP",
                               "DCP",
                               "DCP"), 
                       Field = c("calendar_month", 
                                 "financial_year", 
                                 "geography_level", 
                                 "geography_name", 
                                 "UDAs_annual_contracted", 
                                 "UDAs_delivered_month", 
                                 "UDAs_delivered_month_percent_contracted_standardised", 
                                 "UDAs_delivered_year_to_date", 
                                 "CoT_band1_delivered_incl_FD_standardised", 
                                 "CoT_band2_delivered_incl_FD_standardised",
                                 "CoT_band3_delivered_incl_FD_standardised",
                                 "CoT_urgent_delivered_incl_FD_standardised",
                                 "CoT_other_delivered_incl_FD_standardised",
                                 "CoT_total_delivered_incl_FD_standardised", 
                                 "unique_patients_seen_12_month", 
                                 "unique_children_seen_12_month", 
                                 "unique_adults_seen_24_month", 
                                 "total_NPP_patients_seen", 
                                 "adult_NPP_patients_seen", 
                                 "child_NPP_patients_seen",
                                 "eligible_contracts_for_NPP",
                                 "contracts_seeing_NPP_patients",
                                 "calendar_month",
                                 "financial_year",
                                 "geography_level",
                                 "geography_name",
                                 "UOAs_annual_contracted",
                                 "UOAs_delivered_month",
                                 "UOAs_delivered_month_percent_contracted_standardised",
                                 "UOAs_delivered_year_to_date",
                                 "calendar_month", 
                                 "geography_level", 
                                 "geography_name", 
                                 "DCP_metric", 
                                 "DCP_description", 
                                 "metric_count_by_DCP", 
                                 "metric_count_total", 
                                 "DCP_assisted_percent"), 
                       Description = c("Month the activity was completed for dental course of treatment", 
                                       "Financial year the month belongs to", 
                                       "To aid filtering by National, regional and ICB level data", 
                                       "Name of geography for the measure", 
                                       "Total Annual Contracted UDAs as recorded on BSA Compass system for contracts with Total contracted UDA>100", 
                                       "Total UDAs delivered in the month excluding foundation dentists", 
                                       "Percentage of monthly contracted UDAs delivered in the month excluding foundation dentists, standardised by month length. Denominator standardised as Target UDAs*Monthly working days/working days per year", 
                                       "Total UDAs delivered in the year so far excluding foundation dentists", 
                                       "Total Courses of Treatment for band 1 delivered including foundation dentists, standardised by working days. Standardised as CoT delivered*Monthly working days/working days per year", 
                                       "Total Courses of Treatment for band 2 delivered including foundation dentists, standardised by working days. Standardised as CoT delivered*Monthly working days/working days per year", 
                                       "Total Courses of Treatment for band 3 delivered including foundation dentists, standardised by working days. Standardised as CoT delivered*Monthly working days/working days per year", 
                                       "Total Courses of Treatment for urgent care delivered including foundation dentists, standardised by working days. Standardised as CoT delivered*Monthly working days/working days per year", 
                                       "Total Courses of Treatment for other care delivered including foundation dentists, standardised by working days. Standardised as CoT delivered*Monthly working days/working days per year", 
                                       "Total Courses of Treatment delivered including foundation dentists, standardised by working days. Standardised as CoT delivered*Monthly working days/working days per year", 
                                       "Unique patients seen in a 12 month rolling period, patients seen more than once will be counted once only. Metric is at England and ICB level only. ICB identified by patient postcode", 
                                       "Unique children seen in a 12 month rolling period, children seen more than once will be counted once only. Metric is at England and ICB level only. ICB identified by patient postcode", 
                                       "Unique adults seen in a 12 month rolling period, adults seen more than once will be counted once only. Metric is at England and ICB level only. ICB identified by patient postcode", 
                                       "Number of patients seen in the month under the New Patient Premium definition",
                                       "Number of adults seen in the month under the New Patient Premium definition",
                                       "Number of children seen in the month under the New Patient Premium definition",
                                       "Number of contracts eligible to see patients under the New Patient Premium definition in the month",
                                       "Number of contracts which saw patients in the month under the New Patient Premium definition",
                                       "Month the activity was completed for orthodontic course of treatment",
                                       "Financial year the month belongs to",
                                       "To aid filtering by National, regional and ICB level data",
                                       "Name of geography for the measure",
                                       "Total Annual Contracted UOAs as recorded on BSA Compass system for contracts with Total contracted UOA>1",
                                       "Total UOAs delivered in the month", 
                                       "Percentage of monthly contracted UOAs delivered in the month, standardised by month length. Denominator standardised as Target UOAs*Monthly working days/working days per year",
                                       "Total UOAs delivered in the year so far",
                                       "Month the activity was completed for dental course of treatment", 
                                       "To aid filtering by National, regional and ICB level data", 
                                       "Name of geography for the measure", 
                                       "Identify each Dental Care Practitioner (DCP) metric shown in the SMT pack", 
                                       "Dental Care Practitioner (DCP) description", 
                                       "Counts per metric and per DCP description", 
                                       "Metric totals for all delivery", 
                                       "Percent of metric assisted by DCP description"))











