# create metadata table
metadata <- data.frame(Tab = c("Dental contract and activity", 
                               "Dental contract and activity",
                               "Dental contract and activity",
                               "Dental contract and activity",
                               "Dental contract and activity",
                               "Dental contract and activity",
                               "Dental contract and activity",
                               "Dental contract and activity",
                               "Dental contract and activity",
                               "Dental contract and activity",
                               "Dental contract and activity",
                               "Dental contract and activity",
                               "Dental contract and activity",
                               "Dental contract and activity",
                               "Dental contract and activity",
                               "Dental contract and activity",
                               "Dental contract and activity", 
                               "DCP",
                               "DCP",
                               "DCP",
                               "DCP",
                               "DCP",
                               "DCP",
                               "DCP",
                               "DCP"), 
                       Field = c("calendar_month", 
                                 "financial_year", 
                                 "geography_level", 
                                 "geography_name", 
                                 "UDAs_annual_contracted", 
                                 "UDAs_delivered_month", 
                                 "UDAs_delivered_month_percent_contracted_standardised", 
                                 "UDAs_delivered_year_to_date", 
                                 "CoT_band1_delivered_incl_FD_standardised", 
                                 "CoT_band2_delivered_incl_FD_standardised",
                                 "CoT_band3_delivered_incl_FD_standardised",
                                 "CoT_urgent_delivered_incl_FD_standardised",
                                 "CoT_other_delivered_incl_FD_standardised",
                                 "CoT_total_delivered_incl_FD_standardised", 
                                 "unique_patients_seen_12_month", 
                                 "unique_children_seen_12_month", 
                                 "unique_adults_seen_24_month", 
                                 "calendar_month", 
                                 "geography_level", 
                                 "geography_name", 
                                 "DCP_metric", 
                                 "DCP_description", 
                                 "metric_count_by_DCP", 
                                 "metric_count_total", 
                                 "DCP_assisted_percent"), 
                       Description = c("Month the activity was completed for dental course of treatment", 
                                       "Financial year the month belongs to", 
                                       "To aid filtering by National, regional and ICB level data", 
                                       "Name of geography for the measure", 
                                       "Total Annual Contracted UDAs as recorded on BSA Compass system for contracts with Total contracted UDA>100", 
                                       "Total UDAs delivered in the month excluding foundation dentists", 
                                       "Percentage of monthly contracted UDAs delivered in the month excluding foundation dentists, standardised by month length. Denominator standardised as Target UDAs*Monthly working days/working days per year", 
                                       "Total UDAs delivered in the year so far excluding foundation dentists", 
                                       "Total Courses of Treatment for band 1 delivered including foundation dentists, standardised by working days. Standardised as CoT delivered*Monthly working days/working days per year", 
                                       "Total Courses of Treatment for band 2 delivered including foundation dentists, standardised by working days. Standardised as CoT delivered*Monthly working days/working days per year", 
                                       "Total Courses of Treatment for band 3 delivered including foundation dentists, standardised by working days. Standardised as CoT delivered*Monthly working days/working days per year", 
                                       "Total Courses of Treatment for urgent care delivered including foundation dentists, standardised by working days. Standardised as CoT delivered*Monthly working days/working days per year", 
                                       "Total Courses of Treatment for other care delivered including foundation dentists, standardised by working days. Standardised as CoT delivered*Monthly working days/working days per year", 
                                       "Total Courses of Treatment delivered including foundation dentists, standardised by working days. Standardised as CoT delivered*Monthly working days/working days per year", 
                                       "Unique patients seen in a 12 month rolling period, patients seen more than once will be counted once only. Metric is at England and ICB level only. ICB identified by patient postcode", 
                                       "Unique children seen in a 12 month rolling period, children seen more than once will be counted once only. Metric is at England and ICB level only. ICB identified by patient postcode", 
                                       "Unique adults seen in a 12 month rolling period, adults seen more than once will be counted once only. Metric is at England and ICB level only. ICB identified by patient postcode", 
                                       "Monthly the activity was completed for dental course of treatment", 
                                       "To aid filtering by National, regional and ICB level data", 
                                       "Name of geography for the measure", 
                                       "Identify each Dental Care Practitioner (DCP) metric shown in the SMT pack", 
                                       "Dental Care Practitioner (DCP) description", 
                                       "Counts per metric and per DCP description", 
                                       "Metric totals for all delivery", 
                                       "Percent of metric assisted by DCP description"))











