---
title: "functions for NPP activity monitoring"
---

```{r libraries}
library(tidyverse)
library(odbc)
library(DBI)
```

```{r pull NCDR data}
sql <- "SELECT 
  a.[YEAR_MONTH]
  ,a.[COMMISSIONER_CODE]
  ,b.[STP_Name] AS COMMISSIONER_NAME
  ,b.Region_Name
  ,SUM(a.[NEW_PATIENT_TARIFF_AMOUNT]) AS NPPUDAs
  ,SUM(a.[BAND1_ADULT_COUNT]) + SUM(a.[BAND1_CHILD_COUNT]) + SUM(a.[BAND23_ADULT_COUNT]) + SUM(a.[BAND23_CHILD_COUNT]) AS TotalNPP
  FROM [NHSE_Sandbox_PrimaryCareNHSContracts].[Dental].[Calendar_NPP_Eligible_Activity] a
LEFT JOIN (SELECT DISTINCT
  [Region_Name]
  ,[STP_Name]
  ,[STP_Code]
  FROM [NHSE_Reference].[dbo].[tbl_Ref_ODS_Commissioner_Hierarchies]
  WHERE STP_Code NOT IN ('DUM001', 'DUM002', 'UNK','X24')) b ON a.[COMMISSIONER_CODE] = b.[STP_Code]
  WHERE [EXCLUDE_FROM_NPT] = 'N' AND [YEAR_MONTH] > '2024-02-01'
  GROUP BY a.[COMMISSIONER_CODE], b.Region_Name,b.[STP_Name] , a.[YEAR_MONTH]"

con <- dbConnect(odbc::odbc(), "NCDR")

monthly_delivered_post <- dbGetQuery(con, sql)

dbDisconnect(con)

monthly_delivered_post$Region_Name <- str_to_title(monthly_delivered_post$Region_Name)
monthly_delivered_post$COMMISSIONER_NAME <- str_to_title(monthly_delivered_post$COMMISSIONER_NAME)
monthly_delivered_post$COMMISSIONER_NAME <- substr(monthly_delivered_post$COMMISSIONER_NAME, 5, nchar(monthly_delivered_post$COMMISSIONER_NAME))
monthly_delivered_post$COMMISSIONER_NAME <- str_replace_all(monthly_delivered_post$COMMISSIONER_NAME, "Integrated Care Board", "ICB")
```

```{r load fixed data}
# read in monthly average delivery pre-NPP
# saved to N drive for time being, as it is fixed could upload to NCDR
eden_data <- read.csv("N:/_Everyone/Primary Care Group/SMT_Dental Calendar data format/BSA Calendar data/NPP/npp_eden.csv")
```

```{r create pre-intro data for graph}
# calculate non-paid/pre-intro data for graph
monthly_delivered_pre <- eden_data %>% 
  filter(GROUP != "Post NPP launch - paid (2024/25)") %>% 
  mutate(total = BAND1_ADULT_COUNT + BAND1_CHILD_COUNT + BAND23_ADULT_COUNT + BAND23_CHILD_COUNT,
         financial_year = ifelse(TREATMENT_MONTH <= "202402",
                                 "2023/24", "2024/25"), 
         YEAR_MONTH = as.Date(paste(substr(TREATMENT_MONTH, 1, 4), 
                                    substr(TREATMENT_MONTH, 5, 6), 
                                    "01", sep = "-")))

monthly_delivered_pre$REGION <- str_to_title(monthly_delivered_pre$REGION)
monthly_delivered_pre$COMMISSIONER_NAME <- str_to_title(monthly_delivered_pre$COMMISSIONER_NAME)
monthly_delivered_pre$COMMISSIONER_NAME <- substr(monthly_delivered_pre$COMMISSIONER_NAME, 5, nchar(monthly_delivered_pre$COMMISSIONER_NAME))
monthly_delivered_pre$COMMISSIONER_NAME <- str_replace_all(monthly_delivered_pre$COMMISSIONER_NAME, "Integrated Care Board", "ICB")
```

```{r create comparison}
# calculate eDEN paid post-intro data to compare to NCDR data
monthly_delivered_eden_post <- eden_data %>% 
  filter(GROUP == "Post NPP launch - paid (2024/25)") %>% 
  mutate(total = BAND1_ADULT_COUNT + BAND1_CHILD_COUNT + BAND23_ADULT_COUNT + BAND23_CHILD_COUNT,
         financial_year = ifelse(TREATMENT_MONTH <= "202402",
                                 "2023/24", "2024/25"), 
         YEAR_MONTH = as.Date(paste(substr(TREATMENT_MONTH, 1, 4), 
                                    substr(TREATMENT_MONTH, 5, 6), 
                                    "01", sep = "-")))

monthly_delivered_eden_post$REGION <- str_to_title(monthly_delivered_eden_post$REGION)
monthly_delivered_eden_post$COMMISSIONER_NAME <- str_to_title(monthly_delivered_eden_post$COMMISSIONER_NAME)
monthly_delivered_eden_post$COMMISSIONER_NAME <- substr(monthly_delivered_eden_post$COMMISSIONER_NAME, 5, nchar(monthly_delivered_eden_post$COMMISSIONER_NAME))
monthly_delivered_eden_post$COMMISSIONER_NAME <- str_replace_all(monthly_delivered_eden_post$COMMISSIONER_NAME, "Integrated Care Board", "ICB")

comparison <- monthly_delivered_eden_post %>% 
  group_by(REGION, COMMISSIONER_CODE, COMMISSIONER_NAME, YEAR_MONTH) %>% 
  summarise(total_eden = sum(BAND1_ADULT_COUNT, BAND1_CHILD_COUNT, BAND23_ADULT_COUNT, BAND23_CHILD_COUNT, na.rm = TRUE)) %>% 
  rename(Region_Name = REGION) %>% 
  left_join(monthly_delivered_post, by = c("Region_Name", "COMMISSIONER_CODE", "COMMISSIONER_NAME", "YEAR_MONTH"))
```

```{r calculate figures}
# calculate monthly paid delivered so far
get_npp_data <- function(level = level, 
                         region_STP_name = region_STP_name){
  if(level == "National"){
  
    data_pre <- monthly_delivered_pre %>% 
      filter(REGION == "National") %>% 
      select(YEAR_MONTH, total, financial_year, GROUP)
  
    data_post <- monthly_delivered_post %>% 
      group_by(YEAR_MONTH) %>% 
      summarise(total = sum(TotalNPP, na.rm = TRUE)) %>% 
      mutate(financial_year = "2024/25", 
             GROUP = "Post NPP launch - paid (2024/25)")
  
    } else if(level == "Regional"){
  
      data_pre <- monthly_delivered_pre %>% 
        filter(REGION == region_STP_name) %>% 
        group_by(REGION, TREATMENT_MONTH, GROUP) %>% 
        summarise(total = sum(total)) %>% 
        mutate(financial_year = ifelse(TREATMENT_MONTH <= "202402",
                                       "2023/24", "2024/25"), 
               YEAR_MONTH = as.Date(paste(substr(TREATMENT_MONTH, 1, 4), 
                                          substr(TREATMENT_MONTH, 5, 6), 
                                          "01", sep = "-")))
  
      data_post <- monthly_delivered_post %>% 
        filter(Region_Name == region_STP_name) %>% 
        group_by(Region_Name, YEAR_MONTH) %>% 
        summarise(total = sum(TotalNPP, na.rm = TRUE)) %>% 
        mutate(financial_year = "2024/25", 
               GROUP = "Post NPP launch - paid (2024/25)") %>% 
        rename(REGION = Region_Name)
  
      } else if(level == "ICB"){
  
        data_pre <- monthly_delivered_pre %>% 
          filter(REGION == region_STP_name) %>% 
          group_by(COMMISSIONER_NAME, TREATMENT_MONTH, GROUP) %>% 
          summarise(total = sum(total)) %>% 
          mutate(financial_year = ifelse(TREATMENT_MONTH <= "202402",
                                         "2023/24", "2024/25"), 
                 YEAR_MONTH = as.Date(paste(substr(TREATMENT_MONTH, 1, 4), 
                                      substr(TREATMENT_MONTH, 5, 6), 
                                      "01", sep = "-")))
  
        data_post <- monthly_delivered_post %>% 
          filter(COMMISSIONER_NAME = region_STP_name) %>% 
          group_by(COMMISSIONER_NAME, YEAR_MONTH) %>% 
          summarise(total = sum(TotalNPP, na.rm = TRUE)) %>% 
          mutate(financial_year = "2024/25", 
                 GROUP = "Post NPP launch - paid (2024/25)")
      }
  
  data_combined <- rbind(data_pre, data_post) %>% 
          mutate(month_name = month.name[month(YEAR_MONTH)], 
                 month_name = factor(month_name, 
                                     levels = c("March", "April", "May", "June", "July", "August", 
                                                "September", "October", "November", "December", "January", "February")),
                 GROUP = factor(GROUP, 
                                levels = c("Pre NPP launch (2023/24)", "Post NPP launch - unpaid (2024/25)", "Post NPP launch - paid (2024/25)")))
  }
```

```{r plot chart}
plot_npp_activity_monitoring <- function(level = "National", 
                                         region_STP_name = NULL){
  
  monthly_delivered <- get_npp_data(level = level, 
                                    region_STP_name = region_STP_name)
  
  plt <- ggplot(monthly_delivered, 
                aes(x = financial_year,
                    y = total, 
                    fill = GROUP)) + 
    geom_bar(stat = "identity", position = "stack") + 
    facet_wrap(~month_name, ncol=12, strip.position = "bottom") + 
    xlab("Month") + 
    ylab("Completed courses of treatment") + 
    scale_y_continuous(labels = scales::comma) + 
    scale_fill_manual(values = c("#003087", "#E5C9D9", "#AE2573"),
                      labels = c("Pre NPP launch (2023/24)",
                                 "Post NPP launch - unpaid (2024/25)",
                                 "Post NPP launch - paid (2024/25)")) + 
    theme(panel.border = element_blank(),
          panel.background = element_blank(), 
          strip.background = element_blank(),
          axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          legend.position = "bottom",
          legend.title = element_blank())
  
  plt
}
```

```{r create table}
table_npp_monitoring <- function(level = "National", 
                                 region_STP_name = NULL){
  if(level == "National"){
    
    table_data <- comparison
    
  } else if(level == "Regional"){
    
    table_data <- comparison %>% 
      filter(Region_Name == region_STP_name)
    
  } else if(level == "STP"){
    
    table_data <- comparison %>% 
      filter(COMMISSIONER_NAME == region_STP_name)
  }
  
  table_data <- table_data %>% 
      group_by(YEAR_MONTH) %>% 
      summarise(total_ncdr = sum(TotalNPP, na.rm = TRUE), 
                total_eden = sum(total_eden, na.rm = TRUE)) %>% 
      mutate(pct_diff = (total_ncdr - total_eden)/total_eden, 
             total_ncdr = prettyNum(round(total_ncdr, 0), big.mark = ","), 
             total_eden = prettyNum(round(total_eden, 0), big.mark = ","), 
             pct_diff = paste0(round(pct_diff*100), "%", sep = "")) %>% 
    rename(Month = YEAR_MONTH, 
           COMPASS = total_ncdr,
           eDEN = total_eden, 
           `Percentage difference` = pct_diff)
  
  table_to_print <- tableGrob(table_data, rows = NULL)
}
```
