---
title: "plotting functions for SMT Dental Pack"
---

```{r packages}

library(ggrepel)
library(grid)  # Load the grid package for textGrob

```

```{r get colour palette}
get_colour_palette <- function(){
  
  # The palette with grey:
  c("#E69F00", "#56B4E9", "#009E73", "#0072B2", "#D55E00", "#CC79A7","#F0E442",  "#999999")
  
}
```


```{r UDA/UOA %delivered/contracted - standardised by working days without historical data}

plot_UDA_UOA_delivery_wd <- function(data = UDA_calendar_data, 
                                     UDAorUOA = "UDA",
                                     level = "National",
                                     region_STP_name = NULL,
                                     plotChart = TRUE, 
                                     all_regions_and_STPs = FALSE){
  
  #filter for STP or region-- select the STP or region you want
  if(level == "Regional"){
    
    data <- data %>%
      filter(region_name == region_STP_name)
    subtitle <- region_STP_name
    
  }else if(level == "STP"){
    
    data <- data %>%
      filter(commissioner_name == region_STP_name)
    subtitle <- region_STP_name
    
  }else{
    subtitle <- "England"
  }
  
  if(UDAorUOA == "UDA"){
    
    #get data into the right format if this is for UDA
    data <- get_delivery_data(data = data, UDAorUOA = "UDA", all_regions_and_STPs =all_regions_and_STPs)
    
    #set title and ylab and target of percentage of UDA delivered for each quarter
    title <- "monthly percentage of usual annual contracted UDAs \nsubmitted across all contracts standardised by working days"
    ylab <- "% of contracted UDAs submitted"
    #captionTitle <- "*These are treatment months."
    
    lineCol <- "#CC79A7"
    
    # calculate percentage of delivered UDA standardised by no of working days
    data <- data %>% 
      left_join(working_days,by=c('month')) %>% 
      mutate(perc_standardised_wd_int = 
               100*monthly_UDA_UOAs_delivered /(annual_contracted_UDA_UOA*(`no workdays`/`total workdays`))) %>% 
      mutate(perc_standardised_wd = round(perc_standardised_wd_int, digits = 0))
    
  }else{
    
    #get data into the right format if this is for UOA
    data <- get_delivery_data(data = data, UDAorUOA = "UOA", all_regions_and_STPs = F)
    title <- "monthly percentage of usual annual contracted UOAs \nsubmitted across all contracts standardised by working days"
    ylab <- "% of contracted UOAs submitted"
    #captionTitle <- "**These are treatment months.."
    lineCol <- "steelblue"
    
    # to calculate percentage of delivered UOA standardized by no of working days
    data <- data %>% 
      left_join(working_days,by=c('month')) %>% 
      mutate(perc_standardised_wd_int = 
               100*monthly_UDA_UOAs_delivered /(annual_contracted_UDA_UOA*(`no workdays`/`total workdays`))) %>% 
      mutate(perc_standardised_wd = round(perc_standardised_wd_int, digits = 0))
  }
  
  data <- data %>%
    mutate(month = as.Date(month))
  
  if(plotChart == TRUE){
    
    # plot code
    p <- ggplot(data, 
                aes(x = month, 
                    y = perc_standardised_wd)) +
      theme_bw() +
      geom_line(colour = "blue",
                linewidth = 1) +
      geom_point(colour = lineCol) 
      
      p <- p +
        annotate(geom = "text",
                 x = data$month,
                 y = data$perc_standardised_wd - 3,
                 label = paste0(data$perc_standardised_wd, "%"),
                 size = 3,
                 color="blue")
      
    p <- p +
      scale_x_date(date_breaks = "1 month",
                   date_labels = "%b-%y") +
      scale_y_continuous(limits = c(0, max(c(data$perc_standardised_wd, 95), na.rm = T) + 5),
                         breaks = seq(0, max(c(data$perc_standardised_wd, 95), na.rm = T) + 5, 10)) +
      labs(title = title,
           x = "Month",
           y = ylab,
           subtitle = subtitle) +
      theme(axis.text.x = element_text(angle = 90, vjust=-0.0001))
    
    p
    
  }else{
    
    # what if plotChart == FALSE -- want to create a table instead of a plot
    if(UDAorUOA == "UDA"){
      new_col_names <- c("calendar_month" = "month",
                         "UDAs_delivered_month" = "monthly_UDA_UOAs_delivered",
                         "UDAs_annual_contracted" = "annual_contracted_UDA_UOA",
                         "UDAs_delivered_month_percent_contracted_standardised" = "perc_standardised_wd")
    }else{
      
      new_col_names <- c("calendar_month" = "month",
                         "UOAs_delivered_month" = "monthly_UDA_UOAs_delivered",
                         "UOAs_annual_contracted" = "annual_contracted_UDA_UOA",
                         "UOAs_delivered_month_percent_contracted_standardised" = "perc_standardised_wd")
    }
    
    data$`month` <- format(as.Date(data$`month`), "%Y-%m")
    
    #rename columns
    data <- data %>%
      rename(any_of(new_col_names))
  }
}

```



```{r UDA/UOA %delivered/contracted - standardised by working days without historical data -- include all regions}
plot_UDA_UOA_delivery_all_regions <- function(data = UDA_calendar_data, 
                                              UDAorUOA = "UDA",
                                              level = "National",
                                              region_STP_name = NULL,
                                              plotChart = TRUE, 
                                              all_regions_and_STPs = FALSE){
   
  if(UDAorUOA == "UDA"){
    
    #include data only after 2020-04-01 as there is no region info before that and select fields needed
   data <- data %>%
     mutate(month = as.Date(month)) %>%
     filter(month >= as.Date ("2020-04-01")) %>%
     select(month, contract_number, commissioner_name, region_name, 
             annual_contracted_UDA, UDA_band_1,UDA_band_2,UDA_band_3,UDA_other,UDA_urgent,UDA_delivered)

  # get data into the right format 
  # calculate the annual contracted UDA, delivered UDA and percentage of UDA delivered (standardised by no of working days)
   data <- get_delivery_data(data = data, UDAorUOA = "UDA", all_regions_and_STPs = TRUE)
   data <- data %>%
     filter(month>"2020-03-01")
   
   data <- data %>%
    group_by(month, region_name) %>%
    summarise(monthly_UDA_UOAs_BAND1_delivered = sum(monthly_UDA_UOAs_BAND1_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_BAND2_delivered = sum(monthly_UDA_UOAs_BAND2_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_BAND3_delivered = sum(monthly_UDA_UOAs_BAND3_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_BAND_OTHER_delivered = sum(monthly_UDA_UOAs_BAND_OTHER_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_BAND_URGENT_delivered = sum(monthly_UDA_UOAs_BAND_URGENT_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_delivered = sum(monthly_UDA_UOAs_delivered, na.rm = TRUE),
              annual_contracted_UDA_UOA = sum(annual_contracted_UDA_UOA, na.rm = TRUE)) %>%
    filter(!is.na(region_name))
  

   #percentage of UDA delivered (standardised by no of working days)
   data <- data %>% 
     left_join(working_days,by=c('month')) %>% 
      mutate(perc_standardised_wd_int = 
               100*(monthly_UDA_UOAs_delivered /(annual_contracted_UDA_UOA*(`no workdays`/`total workdays`))))%>% 
      mutate(perc_standardised_wd = round(perc_standardised_wd_int, digits = 0))
   
   title <- "Calendar monthly percentage of usual annual contracted UDAs \nsubmitted across all contracts standardised by working days"
   ylab <- "% of contracted UDAs submitted"
   # captionTitle <- "*These are calendar months and data has been scaled up by 12."
   lineCol <- "coral"
   lineCol <- "#CC79A7"
   
  }else{
    
    #include data only after 2020-04-01 as there is no region info before that and select fields needed
    data <- data %>%
      mutate(month = as.Date(month)) %>%
      filter(month >= as.Date ("2020-04-01")) %>%
      select(month, contract_number, commissioner_name, region_name, 
             annual_contracted_UOA, UOA_band_1,UOA_band_2,UOA_band_3,UOA_other,UOA_urgent,UOA_delivered)
    
    # get data into the right format 
    # calculate the annual contracted UOA, delivered UOA and percentage of UOA delivered (standardized by no of working days)
    data <- get_delivery_data(data = data, UDAorUOA = "UOA", all_regions_and_STPs = TRUE)
    data <- data %>% 
      filter(month>"2020-03-01")
    
    data <- data %>%
      group_by(month, region_name) %>%
      summarise(monthly_UDA_UOAs_BAND1_delivered = sum(monthly_UDA_UOAs_BAND1_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_BAND2_delivered = sum(monthly_UDA_UOAs_BAND2_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_BAND3_delivered = sum(monthly_UDA_UOAs_BAND3_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_BAND_OTHER_delivered = sum(monthly_UDA_UOAs_BAND_OTHER_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_BAND_URGENT_delivered = sum(monthly_UDA_UOAs_BAND_URGENT_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_delivered = sum(monthly_UDA_UOAs_delivered, na.rm = TRUE),
              annual_contracted_UDA_UOA = sum(annual_contracted_UDA_UOA, na.rm = TRUE)) %>%
      filter(!is.na(region_name))
    
    data <- data %>% 
      left_join(working_days,by=c('month')) %>% 
      mutate(perc_standardised_wd_int = 
               100*(monthly_UDA_UOAs_delivered /(annual_contracted_UDA_UOA*(`no workdays`/`total workdays`))))%>% 
      mutate(perc_standardised_wd = round(perc_standardised_wd_int, digits = 0))
    
    title <- "Calendar monthly percentage of usual annual contracted UOAs \nsubmitted across all contracts standardised by working days"
    ylab <- "% of contracted UOAs submitted"
    # captionTitle <- "*These are calendar months and data has been scaled up by 12."
    lineCol <- "coral"
    lineCol <- "#CC79A7"
  }   
    
  if(plotChart == TRUE){
    
    #plot code
    p <- ggplot(data, 
                aes(x = month, 
                    y = perc_standardised_wd, 
                    colour = region_name)) +
      theme_bw() +
      geom_line(size = 1) +
      geom_point() +
      scale_x_date(date_breaks = "1 month", 
                   date_labels = "%b-%y") +
      scale_y_continuous(limits = c(0, max(c(data$perc_standardised_wd, 95), na.rm = T) + 5),
                         breaks = seq(0, max(c(data$perc_standardised_wd, 95), na.rm = T) + 5, 10)) +
      labs(title = title, 
           x = "Month",
           y = ylab, 
           #caption = captionTitle,
           colour = "Region") +
      theme(axis.text.x = element_text(angle = 90, vjust=-0.0001))
    
    p
    
  }else{
   #IF WANT TO GET A DATA TABLE -- rename
    if(UDAorUOA == "UDA"){
      new_col_names <- c("calendar_month" = "month",
                         "UDAs_delivered_month" = "monthly_UDA_UOAs_delivered",
                         "UDAs_annual_contracted" = "annual_contracted_UDA_UOA",
                         "UDAs_delivered_month_percent_contracted_standardised" = "perc_standardised_wd")
    }else{
      
      new_col_names <- c("calendar_month" = "month",
                         "UOAs_delivered_month" = "monthly_UDA_UOAs_delivered",
                         "UOAs_annual_contracted" = "annual_contracted_UDA_UOA",
                         "UOAs_delivered_month_percent_contracted_standardised" = "perc_standardised_wd")
    }
   
    data$`month` <- format(as.Date(data$`month`), "%Y-%m")
    
     data <- data %>%
      rename(any_of(new_col_names))
  }
}
```


```{r UDA/UOA %delivered/contracted - standardised by working days without historical data -- include all ICBs}
plot_UDA_UOA_delivery_all_ICBs <- function(data = UDA_calendar_data,
                                           UDAorUOA = "UOA",
                                           plotChart = TRUE,
                                           region_STP_name='London'){
 
  if(UDAorUOA == "UDA"){
    #include data only after 2020-04-01 and select fields needed
    data <- data %>%
      filter(region_name == region_STP_name)
    
    data <- data %>%
      mutate(month = as.Date(month)) %>%
      filter(month >= as.Date ("2020-04-01")) %>%
      select(month, contract_number, commissioner_name, region_name, annual_contracted_UDA, UDA_band_1,UDA_band_2,UDA_band_3,UDA_other,UDA_urgent,UDA_delivered)
    
    # get data into the right format 
    # calculate the annual contracted UDA, delivered UDA and percentage of UDA delivered (standardized by working days)
    data <- get_delivery_data(data = data, UDAorUOA = "UDA", all_regions_and_STPs = TRUE)
    data <- data %>%
      filter(month>"2020-03-01")
    
    data <- data %>%
      group_by(month, region_name,commissioner_name) %>%
      summarise(monthly_UDA_UOAs_BAND1_delivered = sum(monthly_UDA_UOAs_BAND1_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_BAND2_delivered = sum(monthly_UDA_UOAs_BAND2_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_BAND3_delivered = sum(monthly_UDA_UOAs_BAND3_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_BAND_OTHER_delivered = sum(monthly_UDA_UOAs_BAND_OTHER_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_BAND_URGENT_delivered = sum(monthly_UDA_UOAs_BAND_URGENT_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_delivered = sum(monthly_UDA_UOAs_delivered, na.rm = TRUE),
                annual_contracted_UDA_UOA = sum(annual_contracted_UDA_UOA, na.rm = TRUE)) %>%
      filter(!is.na(region_name))
    
    data <- data %>% left_join(working_days,by=c('month')) %>% 
      mutate(perc_standardised_wd_int = 
               100*(monthly_UDA_UOAs_delivered /(annual_contracted_UDA_UOA*(`no workdays`/`total workdays`))))%>% 
      mutate(perc_standardised_wd = round(perc_standardised_wd_int, digits = 0))
    
    title <- "Calendar monthly percentage of usual annual contracted UDAs \nsubmitted across all contracts standardised by working days"
    ylab <- "% of contracted UDAs submitted"
    # captionTitle <- "*These are calendar months and data has been scaled up by 12."
    lineCol <- "coral"
    lineCol <- "#CC79A7"
    
  }else{
    
    #include only the region/ICB needed -- include data only after 2020-04-01 and select fields needed   
    data <- data %>%
      filter(region_name == region_STP_name)
    
    data <- data %>%
      mutate(month = as.Date(month)) %>%
      filter(month >= as.Date ("2020-04-01")) %>%
      select(month, contract_number, commissioner_name, region_name, 
             annual_contracted_UOA, UOA_band_1,UOA_band_2,UOA_band_3,UOA_other,UOA_urgent,UOA_delivered)
    
    #get data into the right format
    # calculate the annual contracted UOA, delivered UOA and percentage of UOA delivered (standardized by working days)
    data <- get_delivery_data(data = data, UDAorUOA = "UOA", all_regions_and_STPs = TRUE)
    data <- data %>%
      filter(month>"2020-03-01")
    
    data <- data %>%
      group_by(month, region_name,commissioner_name) %>%
      summarise(monthly_UDA_UOAs_BAND1_delivered = sum(monthly_UDA_UOAs_BAND1_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_BAND2_delivered = sum(monthly_UDA_UOAs_BAND2_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_BAND3_delivered = sum(monthly_UDA_UOAs_BAND3_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_BAND_OTHER_delivered = sum(monthly_UDA_UOAs_BAND_OTHER_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_BAND_URGENT_delivered = sum(monthly_UDA_UOAs_BAND_URGENT_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_delivered = sum(monthly_UDA_UOAs_delivered, na.rm = TRUE),
                annual_contracted_UDA_UOA = sum(annual_contracted_UDA_UOA, na.rm = TRUE)) %>%
      filter(!is.na(region_name))
    
    data <- data %>% 
      left_join(working_days,by=c('month')) %>% 
      mutate(perc_standardised_wd_int = 
               100*(monthly_UDA_UOAs_delivered /(annual_contracted_UDA_UOA*(`no workdays`/`total workdays`)))) %>% 
      
      title <- "Calendar monthly percentage of usual annual contracted UOAs \nsubmitted across all contracts standardised by working days"
    ylab <- "% of contracted UOAs submitted"
    # captionTitle <- "*These are calendar months and data has been scaled up by 12."
    lineCol <- "coral"
    lineCol <- "#CC79A7"

  }   
    
  if(plotChart == TRUE){
    
    #plot code
    p <- ggplot(data, 
                aes(x = month, 
                    y = perc_standardised_wd, 
                    colour = commissioner_name)) +
      theme_bw() +
      geom_line(size = 1) +
      geom_point() +
      scale_x_date(date_breaks = "1 month", 
                   date_labels = "%b-%y") +
      scale_y_continuous(limits = c(0, max(c(data$perc_standardised_wd, 95), na.rm = T) + 5),
                         breaks = seq(0, max(c(data$perc_standardised_wd, 95), na.rm = T) + 5, 10)) +
      labs(title = title, 
           x = "Month",
           y = ylab, 
           #caption = captionTitle,
           colour = "commissioner_name") +
      theme(axis.text.x = element_text(angle = 90, vjust=-0.0001))
    
    p
    
  }else{
    
    #if we only need a table instead of a plot -- rename
   if(UDAorUOA == "UDA"){
      new_col_names <- c("calendar_month" = "month",
                         "UDAs_delivered_month" = "monthly_UDA_UOAs_delivered",
                         "UDAs_annual_contracted" = "annual_contracted_UDA_UOA",
                         "UDAs_delivered_month_percent_contracted_standardised" = "perc_standardised_wd")
    }else{
      
      new_col_names <- c("calendar_month" = "month",
                         "UOAs_delivered_month" = "monthly_UDA_UOAs_delivered",
                         "UOAs_annual_contracted" = "annual_contracted_UDA_UOA",
                         "UOAs_delivered_month_percent_contracted_standardised" = "perc_standardised_wd")
    }
    
    data$`month` <- format(as.Date(data$`month`), "%Y-%m")
    data <- data %>%
      rename(any_of(new_col_names))
  }
  
}

```


```{r UDA/UOA %delivered/contracted - standardised by working days without historical data -- include all ICBs -- table}
Table_UDA_UOA_delivery_all_ICBs <- function(data = UOA_calendar_data,
                                            UDAorUOA = "UOA"){

  if(UDAorUOA == "UDA"){
    #include data only after 2020-04-01 and select fields needed
    data <- data %>%
      mutate(month = as.Date(month)) %>%
      filter(month >= as.Date ("2020-04-01")) %>%
      select(month, contract_number, commissioner_name, region_name, annual_contracted_UDA, UDA_band_1,UDA_band_2,UDA_band_3,UDA_other,UDA_urgent,UDA_delivered)
    
    #get data into the right format and calculate the annual contracted UDA, delivered UDA and percentage of UDA delivered
    data <- get_delivery_data(data = data, UDAorUOA = "UDA", all_regions_and_STPs = TRUE)
    data <- data %>%
      filter(month>"2020-03-01")
    
    data <- data %>%
      group_by(month, commissioner_name) %>%
      summarise(monthly_UDA_UOAs_BAND1_delivered = sum(monthly_UDA_UOAs_BAND1_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_BAND2_delivered = sum(monthly_UDA_UOAs_BAND2_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_BAND3_delivered = sum(monthly_UDA_UOAs_BAND3_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_BAND_OTHER_delivered = sum(monthly_UDA_UOAs_BAND_OTHER_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_BAND_URGENT_delivered = sum(monthly_UDA_UOAs_BAND_URGENT_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_delivered = sum(monthly_UDA_UOAs_delivered, na.rm = TRUE),
                annual_contracted_UDA_UOA = sum(annual_contracted_UDA_UOA, na.rm = TRUE))
    
    data <- data %>% 
      left_join(working_days,by=c('month')) %>% 
      mutate(perc_standardised_wd_int = 
               100*(monthly_UDA_UOAs_delivered /(annual_contracted_UDA_UOA*(`no workdays`/`total workdays`))))%>% 
      mutate(perc_standardised_wd = round(perc_standardised_wd_int, digits = 0))
    
   #rename columns
   new_col_names <- c("calendar_month" = "month",
                         "UDAs_delivered_month" = "monthly_UDA_UOAs_delivered",
                         "UDAs_annual_contracted" = "annual_contracted_UDA_UOA",
                         "UDAs_delivered_month_percent_contracted_standardised" = "perc_standardised_wd")
   
   data$`month` <- format(as.Date(data$`month`), "%Y-%m")
   data <- data %>%
      rename(any_of(new_col_names))
   
  }else{
    
    #do similar things for UOA
    data <- data %>%
      mutate(month = as.Date(month)) %>%
      filter(month >= as.Date ("2020-04-01")) %>%
      select(month, contract_number, commissioner_name, region_name,  annual_contracted_UOA, UOA_band_1,UOA_band_2,UOA_band_3,UOA_other,UOA_urgent,UOA_delivered)
    
    #get data into the right format and calculate the annual contracted UDA, delivered UDA and percentage of UDA delivered
    data <- get_delivery_data(data = data, UDAorUOA = "UOA", all_regions_and_STPs = TRUE)
    data <- data %>%
      filter(month>"2020-03-01")
    
    data <- data %>%
      group_by(month, commissioner_name) %>%
      summarise(monthly_UDA_UOAs_BAND1_delivered = sum(monthly_UDA_UOAs_BAND1_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_BAND2_delivered = sum(monthly_UDA_UOAs_BAND2_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_BAND3_delivered = sum(monthly_UDA_UOAs_BAND3_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_BAND_OTHER_delivered = sum(monthly_UDA_UOAs_BAND_OTHER_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_BAND_URGENT_delivered = sum(monthly_UDA_UOAs_BAND_URGENT_delivered, na.rm = TRUE),
              monthly_UDA_UOAs_delivered = sum(monthly_UDA_UOAs_delivered, na.rm = TRUE),
                annual_contracted_UDA_UOA = sum(annual_contracted_UDA_UOA, na.rm = TRUE))
    
    data <- data %>% 
      left_join(working_days,by=c('month')) %>% 
      mutate(perc_standardised_wd_int = 
               100*(monthly_UDA_UOAs_delivered /(annual_contracted_UDA_UOA*(`no workdays`/`total workdays`))))%>% 
      mutate(perc_standardised_wd = round(perc_standardised_wd_int, digits = 0))
    
    new_col_names <- c(`Calendar month` = "month",
                         `Region Name` = "region_name",
                         `Commissioner Name` = "commissioner_name",
                         `Monthly UOAs Band1 delivered` = "monthly_UDA_UOAs_BAND1_delivered",
                         `Monthly UOAs Band2 delivered` = "monthly_UDA_UOAs_BAND2_delivered",
                         `Monthly UOAs Band3 delivered` = "monthly_UDA_UOAs_BAND3_delivered",
                         `Monthly UOAs Band Urgent delivered` = "monthly_UDA_UOAs_BAND_URGENT_delivered",
                         `Monthly UOAs Band Other delivered` = "monthly_UDA_UOAs_BAND_OTHER_delivered",
                         `Monthly UOAs delivered` = "monthly_UDA_UOAs_delivered",
                         `Annual contracted UOAs` = "annual_contracted_UDA_UOA",
                         `Standardised monthly percentage of contracted UOAs delivered` = "perc_standardised_wd")
    
    data$`month` <- format(as.Date(data$`month`), "%Y-%m")
    data <- data %>%
      rename(any_of(new_col_names))
  }   
  
}  

```

```{r number of contracts}
get_num_contracts <- function(data = UDA_calendar_data,
                              UDAorUOA = "UDA",
                              level = "National",
                              region_STP_name = NULL){

  #filter for STP or region in need
  if(level == "Regional"){
    
    data <- data %>% 
      filter(region_name == region_STP_name)
    
  }else if(level == "STP"){
    
    data <- data %>% 
      filter(commissioner_name == region_STP_name)
    subtitle <- region_STP_name
  }
  
  data <- data %>%
    filter(month == max(data$month))
  
  #calculate the no of contractors
  nrow(data)
}

```

```{r UDA activity- standardised by working days with historical data}

plot_historic_UDA_delivery_wd <- function(data = UDA_calendar_data,
                                          level = "National",
                                          region_STP_name = NULL){
  
  #filter for STP or region in need
  if(level == "Regional"){
    data <- data %>%
      filter(region_name == region_STP_name)
    subtitle <- region_STP_name
    
  }else if(level == "STP"){
    
    data <- data %>%
      filter(commissioner_name == region_STP_name)
    subtitle <- region_STP_name
    
  }else{
    
    subtitle <- "England"
  }
  
  #prepare historic data 
  historic_data <- data %>%
    select(month, contract_number, commissioner_name, region_name,
           annual_contracted_UDA, UDA_delivered)
  
  #create a new field as financial year - NEEDS ADDING TO EACH FINANCIAL YEAR
  # calculate full year UDA delivered, contracted UDA and percentage of UDA delivered
  historic_data <- historic_data  %>%
    mutate(financial_year = case_when(month >= as.Date("2019-04-01") & month < as.Date("2020-04-01") ~ "2019/20",
                                      month >= as.Date("2020-04-01") & month < as.Date("2021-04-01") ~ "2020/21",
                                      month >= as.Date("2021-04-01") & month < as.Date("2022-04-01") ~ "2021/22",
                                      month >= as.Date("2022-04-01") & month < as.Date("2023-04-01") ~ "2022/23",
                                      month >= as.Date("2023-04-01") & month < as.Date("2024-04-01") ~ "2023/24"))
  
  historic_latest_contracted_uda <- historic_data %>% 
    group_by(month, financial_year) %>% 
    summarise(final_contracted_UDAs = sum(annual_contracted_UDA, na.rm = TRUE)) %>% 
    filter(month(month) == 3)
  
  historic_data <- historic_data %>% 
    group_by(financial_year) %>% 
    summarise(full_year_UDA_delivery = sum(UDA_delivered, na.rm = TRUE)) %>% 
    left_join(historic_latest_contracted_uda, by = "financial_year") %>% 
    mutate(perc_UDA_delivered = full_year_UDA_delivery * 100 / final_contracted_UDAs)
  
  #get current FY data ready
  # way to calculate percentage of UDA delivered which is standardized by no of working days 
  #calculate UDA_delivery & contracted_UDAs
  data_try <- data %>%
    group_by(month) %>%
    summarise(UDA_delivery = sum(UDA_delivered, na.rm = TRUE),
              contracted_UDAs = sum(annual_contracted_UDA, na.rm = TRUE)) %>%
    # only include current FY data -- calculate percentage of UDA delivered -- standardized by no of working days 
    filter(month >= as.Date ("2024-04-01")) %>% ## this needs to be updated every FY
    left_join(working_days,by=c('month')) %>% 
    mutate(perc_UDA_delivered = 100* (UDA_delivery /(contracted_UDAs*(`no workdays`/`total workdays`)))) %>%
    mutate(perc_UDA_delivered = round(perc_UDA_delivered, digits = 0)) %>% 
    bind_rows(historic_data)
  
  #divide data in to "Previous Financial Years (Averages)", "Current Financial Year"
  data <- data_try %>%
    mutate(year_type = ifelse(is.na(financial_year), "Current Financial Year", 
                              "Previous Financial Years (Averages)"), 
           month = case_when(
             is.na(financial_year) ~ month,
             financial_year == "2019/20" ~ as.Date("2019-04-01"),
             financial_year == "2020/21" ~ as.Date("2020-04-01"),
             financial_year == "2021/22" ~ as.Date("2021-04-01"),
             financial_year == "2022/23" ~ as.Date("2022-04-01"),
             financial_year == "2023/24" ~ as.Date("2023-04-01") # needs adding to each financial year
           ))
  
  data$year_type <- factor(data$year_type, levels = c("Previous Financial Years (Averages)",
                                                      "Current Financial Year"))
  
  data <- data %>% 
    mutate(line_for_100 = 100)
  
  #divide data to two datasets -- previous and current FY
  data1 <- data %>%
    filter(year_type=="Previous Financial Years (Averages)") 
  
  data2 <- data%>%
    filter(year_type=="Current Financial Year") 
  
# Define plot 1
p1 <- ggplot() +
  geom_line(data = data1, aes(x = month, y = perc_UDA_delivered), colour = "black") +
  geom_line(data = data1, aes(x = month, y = line_for_100), colour = "blue") +
  geom_point(data = data1, aes(x = month, y = perc_UDA_delivered), colour = "steelblue") +
  ylab("Percentage of contracted UDAs delivered") +
  xlab(NULL) +
  ggtitle("Previous Financial Years (Averages)") +
  geom_text(data = filter(data1, year_type == "Previous Financial Years (Averages)"),
            aes(x = month + 120, y = perc_UDA_delivered + 4, label = paste0(round(perc_UDA_delivered), "%")),
            size = 3) +
  theme_bw() +
  scale_y_continuous(limits = c(0, max(c(data1$perc_UDA_delivered, 95), na.rm = T) + 5),
                     breaks = seq(0, max(c(data1$perc_UDA_delivered, 95), na.rm = T) + 5, 10)) +
  theme(axis.text.x = element_text(angle = 90, vjust = -0.0001),
        legend.position = "none")

# Define plot 2
p2 <- ggplot() +
  geom_line(data = data2, aes(x = month, y = perc_UDA_delivered), colour = "black") +
  geom_line(data = data2, aes(x = month, y = line_for_100), colour = "blue") +
  geom_point(data = data2, aes(x = month, y = perc_UDA_delivered), colour = "steelblue") +
  ylab(NULL) +
  xlab(NULL) +
  ggtitle("Current Financial Year") +
  geom_text(data = filter(data2, year_type == "Current Financial Year"),
            aes(x = month, y = perc_UDA_delivered + 4, label = paste0(round(perc_UDA_delivered), "%")),
            size = 3) +
  scale_x_date(breaks = "1 month", date_labels = "%b %Y") +
  scale_y_continuous(limits = c(0, max(c(data2$perc_UDA_delivered, 95), na.rm = T) + 5),
                     breaks = seq(0, max(c(data2$perc_UDA_delivered, 95), na.rm = T) + 5, 10)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = -0.0001),
        legend.position = "none")

# Define title and subtitle
main_title <- "Monthly percentage of usual annual contracted UDAs standardised by working days"

# Arrange and annotate figure
figure <- ggarrange(p1, p2, nrow = 1)

# Add footnote
footnote_text <- "Note: Contracts included: GDS/PDS/PDS+ where Total contracted UDA>100.
The most recent two months data will be incomplete and subject to change, particularly for the most recent month. We expect final data to be higher"

# Create annotation
annotation <- annotate_figure(
  figure,
  top = text_grob(paste(main_title, "\n", subtitle), hjust = 0, x = unit(40, "pt"), size = 14),
  bottom = text_grob("Time period")
)

# Add footnote through annotation
annotation2 <- annotate_figure(
  annotation, 
  bottom = textGrob(footnote_text, x = unit(0, "npc"), y = unit(0, "npc") + unit(1, "line"), just = "left", gp = gpar(fontsize = 10, fontface = "italic"))
)

# # Add footnote using grid.text (from grid package)
# grid.arrange(
#   annotation,
#   bottom = textGrob(footnote_text, x = unit(0, "npc"), y = unit(0, "npc") + unit(1, "line"), just = "left", gp = gpar(fontsize = 10, fontface = "italic")),
#   heights = c(1, 0.1)  # Adjust heights as needed
# )

print(annotation2)

}
```

```{r UOA activity data - with historic data}
plot_historic_UOA_delivery_wd <- function(data = UOA_calendar_data,
                                          level = "National",
                                          region_STP_name = NULL){
  
  #filter for STP or region in need
  if(level == "Regional"){
    data <- data %>%
      filter(region_name == region_STP_name )
    
    subtitle <- region_STP_name
    
  }else if(level == "STP"){
    data <- data %>%
      filter(commissioner_name == region_STP_name)
    
    subtitle <- region_STP_name
    
  }else{
    subtitle <- "England"
  }
  
  #prepare historical data
  historic_data <- data %>%
    select(month, contract_number, commissioner_name, region_name,
           annual_contracted_UOA, UOA_delivered)

  # create a new field as financial year - NEEDS ADDING EACH FINANCIAL YEAR
  # then calculate full year UDA delivered, contracted UDA and percentage of UDA delivered
  historic_data <- historic_data  %>%
    mutate(financial_year = case_when(month >= as.Date("2019-04-01") & month < as.Date("2020-04-01") ~ "2019/20",
                                      month >= as.Date("2020-04-01") & month < as.Date("2021-04-01") ~ "2020/21",
                                      month >= as.Date("2021-04-01") & month < as.Date("2022-04-01") ~ "2021/22",
                                      month >= as.Date("2022-04-01") & month < as.Date("2023-04-01") ~ "2022/23",
                                      month >= as.Date("2023-04-01") & month < as.Date("2024-04-01") ~ "2023/24",
                                      month >= as.Date("2024-04-01") & month < as.Date("2025-04-01") ~ "2024/25")) %>%
    group_by(financial_year) %>%
    summarise(full_year_UOA_delivery = sum(UOA_delivered, na.rm = TRUE),
              full_year_contracted_UOAs = sum(annual_contracted_UOA, na.rm = TRUE) / 12) %>%
    mutate(perc_UOA_delivered = full_year_UOA_delivery * 100 / full_year_contracted_UOAs)

  #get current FY data ready
  data_try <- data %>%
    group_by(month) %>%
    summarise(UOA_delivery = sum(UOA_delivered, na.rm = TRUE),
              contracted_UOAs = sum(annual_contracted_UOA, na.rm = TRUE)) %>%
    # only include current FY data -- calculate percentage of UDA delivered -- standardized by no of working days
    filter(month >= as.Date ("2023-04-01")) %>% ## this needs to be updated every FY
    left_join(working_days,by=c('month')) %>% 
    mutate(perc_UOA_delivered =100* (UOA_delivery / (contracted_UOAs*(`no workdays`/`total workdays`)))) %>%
    mutate(perc_UOA_delivered = round(perc_UOA_delivered, digits = 0))%>% 
    #add month for previous FY and create a new variable called financial_year which can be used to join with historical data
    add_row(month = seq(as.Date("2019-04-01"), as.Date("2023-03-01"), lubridate::month(1))) %>%
    mutate(financial_year = case_when(month >= as.Date("2019-04-01") & month < as.Date("2020-04-01") ~ "2019/20",
                                      month >= as.Date("2020-04-01") & month < as.Date("2021-04-01") ~ "2020/21",
                                      month >= as.Date("2021-04-01") & month < as.Date("2022-04-01") ~ "2021/22",
                                      month >= as.Date("2022-04-01") & month < as.Date("2023-04-01") ~ "2022/23",
                                      month >= as.Date("2023-04-01") & month < as.Date("2024-04-01") ~ "2023/24",
                                      month >= as.Date("2024-04-01") & month < as.Date("2025-04-01") ~ "2024/25")) %>%

    left_join(historic_data, by = "financial_year") %>% #join this FY data with historical data 
    mutate(perc_UOA_delivered = if_else(!is.na(perc_UOA_delivered.x), perc_UOA_delivered.x, perc_UOA_delivered.y))
  
  #divide data in to "Previous Financial Years (Averages)", "Current Financial Year"
  data <- data_try %>%
    mutate(year_type = if_else(financial_year == "2024/25", "Current Financial Year", 
                               "Previous Financial Years (Averages)")) %>% 
    # filter April data for previous FY and all current FY data
    filter((substr(month, 6, 7) == "04" & substr(month, 9, 10) == "01")| year_type == "Current Financial Year")
  
  data$year_type <- factor(data$year_type, levels = c("Previous Financial Years (Averages)",
                                                      "Current Financial Year"))
  
  #add a target line
  data<- data %>% 
    mutate(line_for_100 = 100)
  
  ggplot() +
    geom_line(data = data, 
              aes(x = month,
                  y = perc_UOA_delivered),
              colour = "black") + 
    geom_line(data = data, 
              aes(x = month,
                  y = line_for_100),
              colour = "blue") +
    geom_point(data = data,
               aes(x = month,
                   y = perc_UOA_delivered),
               colour = "steelblue") +
    geom_text(data = filter(data, year_type == "Previous Financial Years (Averages)"),
              aes(x = month + 120,
                  y = perc_UOA_delivered - 4,
                  label = financial_year),
              size = 3) +
    geom_text(data = filter(data, year_type == "Previous Financial Years (Averages)"),
              aes(x = month + 120,
                  y = perc_UOA_delivered + 4,
                  label = paste0(round(perc_UOA_delivered), "%")),
              size = 3) +
    geom_text(data = filter(data, year_type == "Current Financial Year"),
              aes(x = month,
                  y = perc_UOA_delivered + 4,
                  label = paste0(round(perc_UOA_delivered), "%")),
              size = 3) +
    facet_wrap(vars(year_type),
               scales = "free_x") +
    theme_bw() +
    scale_y_continuous(limits = c(0, max(c(data$perc_UOA_delivered, 95), na.rm = T) + 5),
                       breaks = seq(0, max(c(data$perc_UOA_delivered, 95), na.rm = T) + 5, 10)) +
    labs(title = "Monthly percentage of usual annual contracted UOAs \nstandardised by working days",
         x = "Time period",
         y = "Percentage of contracted UOAs delivered",
         subtitle = subtitle) +
    theme(axis.text.x = element_text(angle = 90, vjust=-0.0001)) 
}
```

``` {r YTD UDA/UDA delivered}
plot_YTD_UDA_UOA_delivery <- function(data = UDA_calendar_data, 
                                      UDAorUOA = "UDA",
                                      level = "National",
                                      region_STP_name = NULL,
                                      plotChart = TRUE, 
                                      all_regions_and_STPs = FALSE){

  #filter for STP or region in need
  if(level == "Regional"){
    data <- data %>%
      filter(region_name == region_STP_name)
    
    subtitle <- region_STP_name
    
  }else if(level == "STP"){
    data <- data %>%
      filter(commissioner_name == region_STP_name)
    
    subtitle <- region_STP_name
  }else{
    subtitle <- "England"
  }
  
  if(UDAorUOA == "UDA"){
    #get data into the right format for UDA
    data <- get_delivery_data(data, UDAorUOA = "UDA", all_regions_and_STPs = all_regions_and_STPs)
    title <- "YTD UDA delivery across all contracts against annual contracted UDAs (millions)"
    ylab <- "YTD UDA delivery (millions)"
    captionTitle <- "Contracts included: GDS/PDS/PDS+ where Total contracted UDA>100.
    The most recent two months data will be incomplete and subject to change, particularly for the most recent month. We expect final data to be higher."
    lineCol <- "#CC79A7"
    labels <- c("Expected YTD delivery to meet contracted UDAs \nif delivery were equal across the financial year", 
                "Total annual contracted UDAs", 
                "Actual YTD delivery")
  }else{
    #get data into the right format for UOA
    data <- get_delivery_data(data, UDAorUOA = "UOA", all_regions_and_STPs = all_regions_and_STPs)
    title <- "YTD UOA delivery across all contracts against annual contracted UOAs (millions)"
    ylab <- "YTD UOA delivery (millions)"
    captionTitle <- "Contracts included: GDS/PDS/PDS+ where Total contracted UDA>100.
The most recent two months data will be incomplete and subject to change, particularly for the most recent month. We expect final data to be higher."
    lineCol <- "steelblue"
    labels <- c("Expected YTD delivery to meet contracted UOAs \nif delivery were equal across the financial year",

                "Total annual contracted UOAs", 
                "Actual YTD delivery")
  }
  
  # extract previous financial year data -- calculate cumulative sum of monthly_UDA_UOAs_delivered
  historic_data <- data %>% 
    filter(month >= as.Date("2023-04-01") & month <= as.Date("2024-03-01")) %>% ##must be updated each financial year
    mutate(YTD_delivery = cumsum(monthly_UDA_UOAs_delivered))
  
  # extract current financial year data -- calculate cumulative sum of monthly_UDA_UOAs_delivered
  data <- data %>%
    filter(month > as.Date("2024-03-01")) %>% ##must be updated each financial year
    mutate(YTD_delivery = cumsum(monthly_UDA_UOAs_delivered))

  # add latest contracted UDA/UOA as a column to use in plot
  # also add for previous financial year
  # output both as a value to be used in later calculations
  data$latest_annual_contracted_UDA_UOAs <- dplyr::last(data$annual_contracted_UDA_UOA)
  mean_annual_contracted_UDA_UOAs <- dplyr::last(data$annual_contracted_UDA_UOA)
  historic_data$latest_annual_contracted_UDA_UOAs <- dplyr::last(historic_data$annual_contracted_UDA_UOA)
  mean_annual_contracted_UDA_UOAs_historic <- dplyr::last(historic_data$annual_contracted_UDA_UOA)
  
  #add in blanks for the rest of the year
  # NEEDS UPDATING EACH FINANCIAL YEAR
  if(all_regions_and_STPs == FALSE & nrow(data) < 12){
  
    if(!(as.Date("2024-05-01") %in% data$month)){
      data <- data %>% 
        add_row(month = as.Date("2024-05-01"),
                latest_annual_contracted_UDA_UOAs = mean_annual_contracted_UDA_UOAs)
    }
  
    if(!(as.Date("2024-06-01") %in% data$month)){
      data <- data %>% 
        add_row(month = as.Date("2024-06-01"),
                latest_annual_contracted_UDA_UOAs = mean_annual_contracted_UDA_UOAs)
    }
  
    if(!(as.Date("2024-07-01") %in% data$month)){
      data <- data %>% 
        add_row(month = as.Date("2024-07-01"),
                latest_annual_contracted_UDA_UOAs = mean_annual_contracted_UDA_UOAs)
    }
  
    if(!(as.Date("2024-08-01") %in% data$month)){
      data <- data %>% 
        add_row(month = as.Date("2024-08-01"),
                latest_annual_contracted_UDA_UOAs = mean_annual_contracted_UDA_UOAs)
    }
  
    if(!(as.Date("2024-09-01") %in% data$month)){
      data <- data %>% 
        add_row(month = as.Date("2024-09-01"), 
                latest_annual_contracted_UDA_UOAs = mean_annual_contracted_UDA_UOAs)
    }
  
    if(!(as.Date("2024-10-01") %in% data$month)){
      data <- data %>% 
        add_row(month = as.Date("2024-10-01"),
                latest_annual_contracted_UDA_UOAs = mean_annual_contracted_UDA_UOAs)
    }
  
    if(!(as.Date("2024-11-01") %in% data$month)){
      data <- data %>% 
        add_row(month = as.Date("2024-11-01"),
                latest_annual_contracted_UDA_UOAs = mean_annual_contracted_UDA_UOAs)
    }
  
    if(!(as.Date("2024-12-01") %in% data$month)){
      data <- data %>% 
        add_row(month = as.Date("2024-12-01"),
                latest_annual_contracted_UDA_UOAs = mean_annual_contracted_UDA_UOAs)
    }
  
    if(!(as.Date("2025-01-01") %in% data$month)){
      data <- data %>% 
        add_row(month = as.Date("2025-01-01"),
                latest_annual_contracted_UDA_UOAs = mean_annual_contracted_UDA_UOAs)
    }
  
    if(!(as.Date("2025-02-01") %in% data$month)){
      data <- data %>% 
        add_row(month = as.Date("2025-02-01"),
                latest_annual_contracted_UDA_UOAs = mean_annual_contracted_UDA_UOAs)
    }
  
    if(!(as.Date("2025-03-01") %in% data$month)){
      data <- data %>% 
        add_row(month = as.Date("2025-03-01"),
                latest_annual_contracted_UDA_UOAs = mean_annual_contracted_UDA_UOAs)
    }
  }
  
  #add column for expected YTD delivery
  data_to_print <- data %>%
    mutate(expected_delivery = 
             seq(mean_annual_contracted_UDA_UOAs/12, mean_annual_contracted_UDA_UOAs, mean_annual_contracted_UDA_UOAs/12)) %>%
    select(month, YTD_delivery, expected_delivery, latest_annual_contracted_UDA_UOAs)
  
  #pivot for plotting
  data <- data_to_print %>%
    pivot_longer(cols = c("YTD_delivery", "expected_delivery", "latest_annual_contracted_UDA_UOAs"),
                 names_to = "measure", 
                 values_to = "value")

  # format historic data to match current year
  historic_data_to_print <- historic_data %>% 
    mutate(expected_delivery = 
             seq(mean_annual_contracted_UDA_UOAs_historic/12, mean_annual_contracted_UDA_UOAs_historic, 
                 mean_annual_contracted_UDA_UOAs_historic/12)) %>%
    select(month, YTD_delivery, expected_delivery, latest_annual_contracted_UDA_UOAs)

  historic_data <- historic_data_to_print %>% 
    pivot_longer(cols = c("YTD_delivery", "expected_delivery", "latest_annual_contracted_UDA_UOAs"),
                 names_to = "measure", 
                 values_to = "value")

  # bind current and previous financial years
  # pivot so latest contracted UDA or UOAs is a separate column
  data <- rbind(historic_data, data) %>% 
    mutate(year_type = ifelse(month > max(historic_data$month), "Current Financial Year", "Previous Financial Year"))

  data$year_type <- factor(data$year_type, levels = c("Previous Financial Year",
                                                      "Current Financial Year"))  
  
  current_yr_latest_data <- data %>% 
    filter(measure == "YTD_delivery" & value > 0)
  
  current_yr_latest_data <- max(current_yr_latest_data$month)
  
  prev_yr_latest_data <- lubridate::add_with_rollback(current_yr_latest_data, years(-1))
  
  data_labels <- data %>% 
    filter(month %in% c(prev_yr_latest_data, current_yr_latest_data) & measure == "YTD_delivery")
  
  if(plotChart == TRUE){
    #plot code
    p <- ggplot(data, aes(x = month, 
                          y = value/1000000, 
                          colour = measure)) +
      theme_bw() +
      geom_line(aes(linetype = measure),
                size = 1) +
      geom_point() +
      geom_text_repel(aes(label = prettyNum(value, big.mark=",")), 
                      data = data_labels, 
                      colour = "black", 
                      position = "dodge") + 

      scale_x_date(date_breaks = "1 month",
                   date_labels = "%b-%y") +
      labs(title = title,
           x = "Month",
           y = ylab,
           subtitle = subtitle,
           caption = captionTitle,
           colour = "",
           linetype = "") +
        
      theme(axis.text.x = element_text(angle = 90, vjust=-0.0001)) +
      facet_wrap(vars(year_type),
                 scales = "free_x") +
        
      scale_colour_manual(values = c("grey", "black", lineCol), labels = labels) +
      scale_linetype_manual(values = c("dashed", "dashed", "solid"), labels = labels,
                            guide = "none") +
      theme(legend.position="bottom")
    
    p
    
  }else{
    #if want a data table instead
    data_to_print <- data_to_print %>%
      rename(`Calendar month` = month,
             `YTD delivery` = YTD_delivery,
             `Required YTD delivery in order to meet contracted UDAs` = expected_delivery)
    
    data_to_print$`Calendar month` <- format(as.Date(data_to_print$`Calendar month`), "%Y-%m")
  }
}
```

```{r YTD UDA/UOA delivered table}
Table_YTD_UDA_UOA_delivery <- function(data = UDA_calendar_data,
                                       UDAorUOA = "UDA",
                                       level = "National",
                                       all_regions_and_STPs = FALSE){

  if(UDAorUOA == "UDA"){
    #get data into the right format for UDA
    data <- get_delivery_data(data, UDAorUOA = "UDA", all_regions_and_STPs = all_regions_and_STPs)
    
  }else{
    #get data into the right format for UOA
    data <- get_delivery_data(data, UDAorUOA = "UOA", all_regions_and_STPs = all_regions_and_STPs)
  }
  
  data$calendar_month <- format(as.Date(data$`month`), "%Y-%m")
  
  #create a new variable 'financial_year'
  # NEEDS UPDATING EACH FINANCIAL YEAR
  data <- data %>% 
    mutate(financial_year= case_when(month >= as.Date("2019-04-01") & month < as.Date("2020-04-01") ~ "2019/20",
                                     month >= as.Date("2020-04-01") & month < as.Date("2021-04-01") ~ "2020/21",
                                     month >= as.Date("2021-04-01") & month < as.Date("2022-04-01") ~ "2021/22",
                                     month >= as.Date("2022-04-01") & month < as.Date("2023-04-01") ~ "2022/23",
                                     month >= as.Date("2023-04-01") & month < as.Date("2024-04-01") ~ "2023/24",
                                     month >= as.Date("2024-04-01") & month < as.Date("2025-04-01") ~ "2024/25"))
  
  if(level == "Regional"){
    
    #calculate monthly_UDA_UOAs_delivered by `Calendar month`,region_name, financial_year
    #then cumulative sum of YT delivery by financial_year and region
    data <- data %>%
      filter(month >= as.Date ("2020-04-01")) %>%
      group_by(calendar_month,region_name, financial_year) %>%
      summarise(monthly_UDA_UOAs_delivered = sum(monthly_UDA_UOAs_delivered)) %>%
      group_by(region_name, financial_year) %>%
      dplyr::mutate(YTD_delivery = cumsum(monthly_UDA_UOAs_delivered)) %>%
      select(calendar_month,YTD_delivery)
    
  }else if(level == "STP"){
   
    #calculate monthly_UDA_UOAs_delivered by calendar_month,commissioner_name, financial_year
    #then cumulative sum of YT delivery by financial_year and commissioner_name
    data <- data %>%
      filter(month >= as.Date ("2020-04-01")) %>%
      group_by(calendar_month,commissioner_name, financial_year) %>%
      summarise(monthly_UDA_UOAs_delivered = sum(monthly_UDA_UOAs_delivered)) %>%
      group_by(commissioner_name, financial_year) %>%
      dplyr::mutate(YTD_delivery = cumsum(monthly_UDA_UOAs_delivered)) %>%
      select(calendar_month,YTD_delivery)
   
  }else{

#calculate cumulative sum of YTD delivery by financial_year
    data <- data %>%
      arrange(calendar_month) %>%
      group_by(financial_year) %>% 
      dplyr::mutate(YTD_delivery = cumsum(monthly_UDA_UOAs_delivered)) %>%
      select(calendar_month,YTD_delivery)
  }
}
  
```

```{r monthly UDA delivered}
plot_monthly_uda_delivered <- function(data = UDA_calendar_data, 
                                       level = "National", 
                                       region_STP_name = NULL){
  # filter for STP or region - select the STP or region you want
  if(level == "Regional"){
    data <- data %>% 
      filter(region_name == region_STP_name)
    subtitle <- region_STP_name
    } else if(level == "STP"){
      data <- data %>% 
        filter(commissioner_name == region_STP_name)
      subtitle <- region_STP_name
      } else {
        subtitle <- "England"
        }
  
  data <- data %>% 
    filter(month >= "2023-04-01" & month <= "2025-03-01") %>% # needs updating every financial year
    group_by(month) %>% 
    summarise(uda_delivered = sum(UDA_delivered, na.rm = TRUE)) %>% 
    mutate(financial_year = ifelse(month <= "2024-03-01", "2023/24", "2024/25"), 
           month_name = format(month, "%B"))

  # set month names to the right order
  data$month_name <- factor(data$month_name, 
                            levels = c("April", "May", "June", "July", "August", "September", "October",
                                       "November", "December", "January", "February", "March"))
  
  latest_complete_month <- format(max(data$month)-58, "%B")
  
  data_labels <- data %>% 
    filter(month_name == latest_complete_month)

  ggplot(data, aes(x = month_name, y = uda_delivered, fill = financial_year)) + 
    geom_bar(position = "dodge", stat = "identity") + 
    geom_text(aes(label = prettyNum(uda_delivered, big.mark=",")), 
              data = data_labels,
              colour = "black",
              vjust = -0.5, 
              position = position_dodge(.9)) + 
    theme_bw() +
    theme(legend.position = "bottom") + 
    labs(title = "Monthly UDAs delivered", 
         subtitle = subtitle, 
         x = "Month", 
         y = "UDAs delivered", 
         caption = "Contracts included: GDS/PDS/PDS+ where Total contracted UDA>100.
The most recent two months data will be incomplete and subject to change, particularly for the most recent month. We expect final data to be higher.") + 
    scale_fill_manual(values = get_colour_palette(), name = "") + 
    scale_y_continuous(labels = function(x) format(x, big.mark = ",", scientific = FALSE))
}
```


```{r banded_CoT}
plot_banded_CoT <- function(data = UDA_calendar_data_FD, 
                            level = "National", 
                            region_STP_name = NULL, 
                            plotChart = TRUE, 
                            all_regions_and_STPs = FALSE, 
                            asIndex = FALSE){
  
  #avoid standard form on axes
  options(scipen = 100)
  
  #toggle subtitle
  if(level == "Regional"){
    
    #filter for region or STP
    # start from 2020-04-01 as region information not available before then
    data <- data %>% 
      filter(region_name == region_STP_name,
             month >= "2020-04-01")
    subtitle <- region_STP_name 
    
  }else if(level == "STP"){
    
    #filter for region or STP
    # start from 2020-04-01 as region information not available before then
    data <- data %>% 
      filter(commissioner_name == region_STP_name, 
             month >= "2020-04-01")
    subtitle <- region_STP_name
    
  }else{
    subtitle <- "England"
    data <- data
  }
  
  #get data into the right format
  data_to_print <- get_banded_COTs_data(data, all_regions_and_STPs = all_regions_and_STPs)
  data <- reshape2::melt(data_to_print, id.vars = "month")
  data <- data %>%
    mutate(month = as.Date(month)) %>%
    rename(band = variable, CoTs = value)  %>% 
    filter(band != "region_name")
  
  
  if(asIndex == TRUE){
    
    #set everything as index of Feb 2020 and standardise for working days
    data <- data %>%
      left_join(working_days,by=c('month')) %>% 
      mutate(standardised_CoTs = CoTs *(`no workdays`/`total workdays`), 
             month_number = substr(month, 6, 7), 
             year_number = substr(month, 1, 4))
    
    dataFeb2020 <- data %>% 
      filter(year_number == "2020" & month_number == "02") %>% 
      select(month_number, band, 
             CoTs_feb2020 = CoTs)
    
    data <- data %>% 
      left_join(dataFeb2020, by = c("band")) %>% 
      mutate(CoTs = CoTs * 100 / CoTs_feb2020)
    
    title <- "Banded Courses of Treatment as a Percentage of February 2020 Delivery Including Foundation Dentists"
    ylab <- "Percentage of February 2020 completed CoT"
    caption <- "Contracts included: GDS/PDS/PDS+ where Total contracted UDA>100.
The most recent two months data will be incomplete and subject to change, particularly for the most recent month. We expect final data to be higher.
This chart includes foundation dentists so total counts will differ to other charts."
    
  }else{ # or standardise for working days only
    data <- data %>% left_join(working_days,by=c('month')) %>% 
      mutate(standardised_CoTs = CoTs *(`no workdays`/`total workdays`)) %>%
      select(-CoTs) %>% 
      rename(CoTs = standardised_CoTs)
      
      title <- "Banded Courses of Treatment Including Foundation Dentists"
      ylab <- "Number of completed Courses of Treatment"

      caption <- "Contracts included: GDS/PDS/PDS+ where Total contracted UDA>100.
The most recent two months data will be incomplete and subject to change, particularly for the most recent month. We expect final data to be higher.
This chart includes foundation dentists so total counts will differ to other charts."
    }

  
  data_labels <- data %>%
    filter(month == max(month)) %>% 
    mutate(CoTs = round(CoTs))
  
  if(plotChart == TRUE){
    
    #plot code
    ggplot(data, aes(x = month, 
                     y = CoTs, 
                     colour = band)) +
      theme_bw() +
      theme(axis.text.x = element_text(angle = 90)) +
      geom_line(size = 1) +
      geom_point(size = 1) +
      geom_text_repel(aes(label = prettyNum(CoTs, big.mark=",")), 
                      data = data_labels, 
                      colour = "black", 
                      position = "dodge") +
      scale_x_date(breaks = function(x) seq.Date(from = min(data$month), to = max(data$month), by = "1 month"), 
                   date_labels = "%b-%y") +
      scale_colour_manual(labels = c("Band 1", "Band 2", "Band 3", "Other", "Urgent"),
                          values = get_colour_palette()) +
      scale_y_continuous(breaks = scales::breaks_pretty(),
                         labels = function(x) format(x, big.mark = ",", scientific = FALSE)) +
      labs(title = title,
           x = "Month",
           y = ylab,
           colour = "Band",

           subtitle = subtitle,
           caption = caption)

  }else{
    
  data <- data_to_print %>%
    mutate(month = format(as.Date(month), "%Y-%m"))
  }
}
```

```{r table_banded_CoT}
table_banded_CoT <- function(data = UDA_calendar_data_FD, 
                             level = "National", 
                             all_regions_and_STPs = FALSE, 
                             asIndex = FALSE){
  
  #get data into the right format for banded_CoT
  data_to_print <- get_banded_COTs_data(data, all_regions_and_STPs = all_regions_and_STPs)
  
  if(level == "Regional"){
    # filter for region or STP
    # start from 2020-04-01 as geographic information not available before then
    #calculate in each band
    data_to_print <- reshape2::melt(data_to_print, id.vars = c("month", "region_name"))
    
    data <- data_to_print %>%
          filter(variable != "commissioner_name") %>% 
          left_join(working_days, by = c("month")) %>%
          mutate(month = format(as.Date(month), "%Y-%m"),
                 CoTs = as.numeric(value),
                 standardised_CoTs = CoTs*(`no workdays`/`total workdays`)) %>% 
          group_by(month, region_name, variable) %>% 
          summarise(standardised_CoTs = sum(standardised_CoTs, na.rm = TRUE)) %>% 
          pivot_wider(names_from = variable, values_from = standardised_CoTs)

    }else if(level == "STP"){
      
      #filter for region or STP
      # start from 2020-04-01 as geographic information not available before then
      #calculate in each band
      data_to_print <- reshape2::melt(data_to_print, id.vars = c("month", "commissioner_name"))
      
      data <- data_to_print %>%
          filter(variable != "region_name") %>% 
          left_join(working_days, by = c("month")) %>%
          mutate(month = format(as.Date(month), "%Y-%m"),
                 CoTs = as.numeric(value),
                 standardised_CoTs = CoTs*(`no workdays`/`total workdays`)) %>% 
          group_by(month, commissioner_name, variable) %>% 
          summarise(standardised_CoTs = sum(standardised_CoTs, na.rm = TRUE)) %>% 
          pivot_wider(names_from = variable, values_from = standardised_CoTs)
      
      }else{
        #at national level
        #calculate in each band
        data_to_print <- reshape2::melt(data_to_print, id.vars = c("month"))
        
        data <- data_to_print %>%
          left_join(working_days, by = c("month")) %>%
          mutate(month = format(as.Date(month), "%Y-%m"),
                 CoTs = as.numeric(value),
                 standardised_CoTs = CoTs*(`no workdays`/`total workdays`)) %>% 
          group_by(month, variable) %>% 
          summarise(standardised_CoTs = sum(standardised_CoTs, na.rm = TRUE)) %>% 
          pivot_wider(names_from = variable, values_from = standardised_CoTs)
        }
}
```

```{r 111 dental}

plot_111_referrals <- function(data = dental_data_111,
                               plotChart = TRUE){
  
  #calculate case volume for each month
  data <- data %>% 
    mutate(month = as.Date(month)) %>%
    group_by(month) %>%
    summarise(monthly_case_volume = sum(monthly_case_volume))
  
  data_labels <- data %>% 
    filter(month == max(month))
  
  #plot code
  p <- ggplot(data, 
              aes(x = month, 
                  y = monthly_case_volume)) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90)) +
    geom_line(colour = "steelblue", 
              size = 1) +
    geom_text_repel(aes(label = prettyNum(monthly_case_volume, big.mark = ",")), 
                    data = data_labels, 
                    colour = "black", 
                    position = "dodge") +
    scale_x_date(breaks = function(x) seq.Date(from = min(data$month), to = max(data$month), by = "1 month"), 
                 date_labels = "%b-%y") +
    scale_y_continuous(breaks = seq(0, 
                                    max(data$monthly_case_volume, na.rm = T) + 10000,
                                    10000),
                       limits = c(0, max(data$monthly_case_volume))) +
    labs(title = "111 call volume recommended towards dental services", 
         x = "Month",
         y = "Call volume", 
         subtitle = "England",
         caption = "* This data is 1 month behind other data in this pack."
    )
  
  if(plotChart == TRUE){
    
    p
    
  }else{
    
    data
    
  }
}

```

```{r  breakdown_111_referrals}

plot_breakdown_111_referrals <- function(data = dental_data_111,
                                         plotChart = TRUE){
  
  #replace disposition_text == "Attend Emergency Dental Treatment Centre within 4" to "Attend Emergency Dental Treatment Centre within 4hrs"
  data <- data %>% 
    mutate(disposition_text = if_else(disposition_text == "Attend Emergency Dental Treatment Centre within 4",
                                      "Attend Emergency Dental Treatment Centre within 4hrs",
                                      disposition_text)) %>%
    mutate(month = as.Date(month)) 
  
  #get disposition_text lines in the right order
  data$disposition_text <- factor(data$disposition_text,
                                  levels = c("Refer to Dental Treatment Centre within 1 hour",
                                             "Refer to Dental Treatment Centre within 4 hours",
                                             "To Speak to a Dental Service within 1 hour",
                                             "To Speak to a Dental Service within 2 hours",
                                             "Speak to a Dental Service within 2 hours",
                                             "To Speak to a Dental Service within 6 hours",
                                             "To Speak to a Dental Service within 12 hours",
                                             "To Speak to a Dental Service within 24 hours",
                                             "To Speak to a Dental Practice within 7 days",
                                             "Contact Orthodontist next working day"))
  
  #plot code
  p <- ggplot(data) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90)) +
    geom_line(aes(x = month, 
                  y = monthly_case_volume,
                  colour = str_wrap(disposition_text, 35)), 
              size = 1) +
    scale_x_date(date_breaks = "1 month", 
                 date_labels = "%b-%y") +
    labs(title = "111 call volume recommended towards dental services", 
         x = "Month",
         y = "Call volume", 
         subtitle = "England",
         colour = "Disposition"#,
         #caption = "*services include: "
    )
  
  if(plotChart == TRUE){
    
    p
  }else{
    
    data %>%
      select(`Month` = month,
             `Disposition` = disposition_text,
             `Monthly case volume` = monthly_case_volume)
  }
  
}
```


```{r unique patients rolling}

plot_unique_patients_rolling <- function(data = unique_patients_rolling, 
                                         level = "National", 
                                         region_STP_name = NULL, 
                                         plotChart = TRUE, 
                                         all_regions_and_STPs = FALSE, 
                                         asIndex = FALSE){
  
  #get data in the right format for unique_patients
  data <- get_unique_patients()
  
  options(scipen = 5)

chartCaption <- "Contracts included: GDS/PDS/PDS+
Includes all patients seen
The most recent two months data will be incomplete and subject to change, particularly for the most recent month. We expect final data to be higher.
Unique patients are based on ICB of patient home postcode, each patient is counted only once and allocated to an ICB as identified by their most recent FP17 patient postcode.
Patients without a postcode are excluded from this analysis. NHS England and BSA are working together to alter this metric in the future so that it matches the planning guidance metrics.
This does not impact the data at an England level."

#set subtitles
if(level == "STP"){
  subtitle <- region_STP_name
}else{
  subtitle <- "England"
}

if(plotChart == TRUE & asIndex == FALSE){
  #rename -- pivot to get the right format
  data <- data %>% 
  rename(`All (12 month rolling period)` = all_12m_count, 
         `Children (12 month rolling period)` = child_12m_count, 
         `Adults (24 month rolling period)` = adult_24m_count) %>% 
  pivot_longer(!month) %>% 
  rename(total_unique_patients = value)
  
  title <- "Total number of unique patients seen over a rolling 12 or 24 month period"
  ylab <- "Unique patients"
  
  data_labels <- data %>% 
    filter(month == max(month))
  
  #plot code
  ggplot(data, aes(x = month, 
                   y = total_unique_patients, 
                   colour = name)) +
    theme_bw() +
    geom_line() +
    geom_point() +
    geom_text_repel(aes(label = prettyNum(total_unique_patients, big.mark=",")), 
                    data = data_labels, 
                    colour = "black", 
                    position = "dodge") + 
    scale_y_continuous(labels=function(x) format(x, big.mark = ",", scientific = FALSE)) +
    scale_colour_manual(values = get_colour_palette(), 
                        name = "") +
    labs(title = title,
         x = "12 or 24 month rolling period end date",
         y = ylab,
         subtitle = subtitle,
         caption = chartCaption
    ) +
    scale_x_date(breaks = function(x) seq.Date(from = min(data$month), to = max(data$month), by = "1 month"), 
                 date_labels = "%b-%y") +
    theme(axis.text.x = element_text(angle = 90))
  
} else if(plotChart == TRUE & asIndex == TRUE){
  
  #rename
  data <- data %>% 
  rename(`All (12 month rolling period)` = all_12m_count, 
         `Children (12 month rolling period)` = child_12m_count, 
         `Adults (24 month rolling period)` = adult_24m_count)
  
  #reshape to the right format
  data <- reshape2::melt(data, id.vars = "month")


  #Feb 2020 has been used as an reference
  dataFeb2020 <- data %>% 
      filter(month == "2020-02-01") %>% 
      rename(value_Feb2020 = value)

  
    data <- data %>% 
      left_join(dataFeb2020, by = c("variable")) %>% 
      mutate(value = value * 100 / value_Feb2020) %>% 
      select(-month.y) %>% 
      rename(month = month.x)

    title <- "Total number of unique patients seen over a rolling 12 or 24 month period as a percentage of February 2020 figures"
    ylab <- "Percentage of February 2020 unique patients"
    
    data_labels <- data %>% 
      filter(month == max(month))
  
    data$variable <- factor(data$variable, 
                            levels = c("Adults (24 month rolling period)", 
                                       "Children (12 month rolling period)", 
                                       "All (12 month rolling period)"))
    
    #plot code
    ggplot(data, 
           aes(x = month,
               y = value,
               colour = variable)) +
      theme_bw() +
      geom_line() +
      geom_point() +
    geom_text_repel(aes(label = round(value)), 
                    data = data_labels, 
                    colour = "black", 
                    position = "dodge") + 
      scale_y_continuous(labels=function(x) format(x, big.mark = ",", scientific = FALSE)) +
      scale_colour_manual(values = get_colour_palette(), 
                          name = "") +
      labs(title = title,
           x = "12 or 24 month rolling period end date",
           y = ylab,
           subtitle = subtitle,
           caption = chartCaption) +
      scale_x_date(breaks = function(x) seq.Date(from = min(data$month), to = max(data$month), by = "1 month"), 
                   date_labels = "%b-%y") +
      theme(axis.text.x = element_text(angle = 90))
  }
}
```

```{r DCP1}

plot_DCP_analysis <- function(data = UDA_calendar_data,
                              dcp_data = DCP_data,
                              UDA_or_FP17 = "FP17",
                              level = "National",
                              region_STP_name = NULL){
  
  dcp_data <- dcp_data %>%
    rename(month = Month)
  
  #filter for region or STP
  if(level == "Regional"){
    
    data <- data %>% 
      filter(region_name == region_STP_name )
    
    dcp_data <- dcp_data %>%
      filter(Region == region_STP_name)
    
    subtitle <- region_STP_name 
    
  }else if(level == "STP"){
    
    data <- data %>% 
      filter(commissioner_name == region_STP_name)
    
    dcp_data <- dcp_data %>%
      filter(commissioner_name == region_STP_name)
    
    subtitle <- region_STP_name
    
  }else{
    subtitle <- "England"
  }
  
  #calculate total FP19, UDA_B1, B2, B3 and urgent by month for "Total_dentist_only_and_DCP_assisted' by using UDA Calendar data
  delivery_total <-  data %>% 
    group_by(month) %>%
    dplyr::summarise( total_FP17 = sum(general_FP17s, na.rm = TRUE),
                      total_B1 = sum(UDA_band_1, na.rm = TRUE),
                      total_B2 = sum(UDA_band_2, na.rm = TRUE),
                      total_B3 = sum(UDA_band_3, na.rm = TRUE),
                      total_urgent = sum(UDA_urgent, na.rm = TRUE)) %>%
    mutate(DCP_description = "Total_dentist_only_and_DCP_assisted") %>%
    select(month, DCP_description, total_FP17,total_B1, total_B2, total_B3, total_urgent) %>% 
    rename(`Band 1` = total_B1, `Band 2` = total_B2, `Band 3` = total_B3, Urgent = total_urgent)
  
  #calculate total FP19, UDA_B1, B2, B3 and urgent by month for separate DCP description by using DCP data
  dcp_main_new <- dcp_data %>% 
    filter(DCP_description != 'Clinical Technician') %>%
    filter(DCP_description != 'Technician') %>%
    mutate(DCP_description = replace(DCP_description, DCP_description== "Nurse", "Dental_Nurse_assisted"), 
           DCP_description = replace(DCP_description, DCP_description=="Dental Hygienist", "Hygienist_assisted"), 
           DCP_description = replace(DCP_description, DCP_description=="Dental Therapist", "Therapist_assisted"),
           DCP_description = replace(DCP_description, DCP_description=="Hygienist", "Hygienist_assisted"), 
           DCP_description = replace(DCP_description, DCP_description=="Therapist", "Therapist_assisted"))
  
  dcp_summary <- dcp_main_new %>% 
    filter(!is.na(DCP_description))%>%
    group_by(month, DCP_description) %>%
    summarise (total_FP17 = sum(FP17_Current_Year_total, na.rm = TRUE),
               total_B1 = sum(Band_1._UDA, na.rm = TRUE),
               total_B2 = sum(Band_2._UDA, na.rm = TRUE),
               total_B3 = sum(Band_3._UDA, na.rm = TRUE),
               total_urgent = sum(Urgent_UDA, na.rm = TRUE)) %>% 
    rename(`Band 1` = total_B1, `Band 2` = total_B2, `Band 3` = total_B3, Urgent = total_urgent)

#pivot delivery total and seperate dcp into long format
  dcp_summary_longer <- dcp_summary %>% 
    pivot_longer(cols = starts_with("total"),
                 names_to = "Bands",
                 names_prefix = "dcp",
                 values_to = "numbers",
                 values_drop_na = TRUE) 
  
  delivery_total_longer <- delivery_total %>% 
    pivot_longer(cols = starts_with("total"),
                 names_to = "Bands",
                 names_prefix = "dcp",
                 values_to = "all_numbers",
                 values_drop_na = TRUE)
  
  #join total and separate dcp to get the full data ready for plot
  all_lookup <- left_join(dcp_summary_longer, delivery_total_longer, 
                          by = c("month", "Bands"))
  
  #calculate the percentage of each dcp description/total delivery 
  total <- all_lookup %>% 
    mutate(assisted_percent = formattable::percent (numbers / all_numbers, digits=2))
  
  if(UDA_or_FP17 == "UDA"){
    
    #UDA is only for those with 'band'
    filtered_data_UDA = filter(total, Bands %in% c("Band 1",	"Band 2",	"Band 3", "Urgent")) %>%
      select(month, "DCP_description.x", "Bands", "assisted_percent") %>%
      rename (DCP_description = DCP_description.x) %>%
      mutate(month = as.Date(month)) %>%
      mutate(DCP_description = str_replace_all(DCP_description, "_", " "))
    
    max_month <- max(filtered_data_UDA$month)
    
    data_labels <- filtered_data_UDA %>% 
      filter(month == max_month)


    UDA_plot <- ggplot(filtered_data_UDA,
                       aes(x = month, y = assisted_percent)) +
      facet_grid(cols = vars(DCP_description)) +
      geom_line(aes(colour = Bands),
                size = 1) +
      geom_text_repel(aes(label = assisted_percent), 
                      data = data_labels, 
                      colour = "black", 
                      position = "dodge") +
      scale_fill_manual(values = c("#009E73", "#F0E442", "#D55E00"),
                        labels = c("Dental Nurse assisted", "Hygienist", "Therapist")) +
      scale_x_date(date_breaks = "1 month",
                   date_labels = "%b-%y") +
      theme_bw() +
      labs(title = "Percentage of total UDAs delivered which had Dental Care Practitioner (DCP) assistance by DCP roles",
           subtitle = subtitle,
           x = "Month",
           y = "Percentage of total UDAs delivered",
           colour = "Bands",
           caption = "Contracts included: GDS/PDS/PDS+ where Total contracted UDA>100
           The most recent two months data will be incomplete and subject to change, particularly for the most recent month. We expect final data to be higher.") + 
      scale_y_continuous(labels = scales::percent)+
      theme(axis.text.x = element_text(angle = 90, vjust=-0.0001))

    UDA_plot



  }else{
    
    #UDA is only for those with 'total_FP17'
    filtered_data_FP17 <- total %>%
      filter( Bands %in% c("total_FP17")) %>% 
      select("month", "DCP_description.x", "Bands", "assisted_percent") %>%
      mutate(month = as.Date(month)) %>%
      rename ( Percent_of_FP17 = Bands, DCP_description = DCP_description.x) %>%
      mutate(DCP_description = str_replace_all(DCP_description, "_", " ")) 
    
    #get the number for the latest month -- used for label in the plot
    latest_month <- max(filtered_data_FP17$month)
    latest_data <- filtered_data_FP17 %>%
    filter(month == latest_month)

    FP17_plot <- ggplot(filtered_data_FP17, 
                        aes(x=month, y= assisted_percent)) +
      geom_line(aes(colour = DCP_description),
                size = 1) +
      geom_text_repel(data = latest_data, aes(label = assisted_percent), 
                    colour = "black", size = 3.5, vjust = -0.25) + 
      theme(legend.position="bottom") +
      theme_bw() +
      scale_x_date(date_breaks = "1 month",
                   date_labels = "%b-%y") +
      labs(title = "Percentage of total Courses of Treatment (CoTs) delivered which had Dental Care Practitioner (DCP) assistance",
           subtitle = subtitle,
           x = "Month",
           y = "Percentage of total CoTs delivered",
           colour = "DCP description",
           caption = "Contracts included: GDS/PDS/PDS+ where Total contracted UDA>100
           The most recent two months data will be incomplete and subject to change, particularly for the most recent month. We expect final data to be higher.") + 
      scale_y_continuous(labels = scales::percent)  +
      theme(axis.text.x = element_text(angle = 90, vjust=-0.0001))
    
    FP17_plot

    
  }
}

plot_DCP_analysis_regional_check <- function(data = UDA_calendar_data,
                                             dcp_data = DCP_data,
                                             UDA_or_FP17 = "UDA",
                                             level = "National",
                                             region_STP_name = NULL){
  
  dcp_data <- dcp_data %>%
    rename(month = Month)
  
  #filter for region or STP
  if(level == "Regional"){
    data <- data %>% 
      filter(region_name == region_STP_name )
    
    dcp_data <- dcp_data %>%
      filter(Region == region_STP_name)
    
    subtitle <- region_STP_name 
  }else if(level == "STP"){
    data <- data %>% 
      filter(commissioner_name == region_STP_name)
    
    dcp_data <- dcp_data %>%
      filter(commissioner_name == region_STP_name)
    
    subtitle <- region_STP_name
  }else{
    subtitle <- "England"
  }
  
  colnames(UDA_calendar_data)
  
   #calculate total FP19, UDA_B1, B2, B3 and urgent by month for "Total_dentist_only_and_DCP_assisted' by using UDA Calendar data
  delivery_total <-  data %>% 
    rename(Region = region_name) %>%
    group_by(month, Region) %>%
    dplyr::summarise( total_FP17 = sum(general_FP17s, na.rm = TRUE),
                      total_B1 = sum(UDA_band_1, na.rm = TRUE),
                      total_B2 = sum(UDA_band_2, na.rm = TRUE),
                      total_B3 = sum(UDA_band_3, na.rm = TRUE),
                      total_urgent = sum(UDA_urgent, na.rm = TRUE)) %>%
    mutate (DCP_description = "Total_dentist_only_and_DCP_assisted") %>%
    select (month, Region, DCP_description, total_FP17,total_B1, total_B2, total_B3, total_urgent)
  
   #calculate total FP19, UDA_B1, B2, B3 and urgent by month for separate DCP description by using DCP data
  dcp_main_new <- dcp_data %>% 
    filter(DCP_description != 'Clinical Technician') %>%
    filter(DCP_description != 'Technician') %>%
    mutate(DCP_description = replace(DCP_description, DCP_description== "Nurse", "Dental_Nurse_assisted"), 
           DCP_description = replace(DCP_description, DCP_description=="Dental Hygienist", "Hygienist_assisted"), 
           DCP_description = replace(DCP_description, DCP_description=="Dental Therapist", "Therapist_assisted"),
           DCP_description = replace(DCP_description, DCP_description=="Hygienist", "Hygienist_assisted"), 
           DCP_description = replace(DCP_description, DCP_description=="Therapist", "Therapist_assisted"))
  
  dcp_summary <- dcp_main_new %>% 
    group_by(month, Region, DCP_description) %>%
    summarise (total_FP17 = sum(FP17_Current_Year_total, na.rm = TRUE),
               total_B1 = sum(Band_1._UDA, na.rm = TRUE),
               total_B2 = sum(Band_2._UDA, na.rm = TRUE),
               total_B3 = sum(Band_3._UDA, na.rm = TRUE),
               total_urgent = sum(Urgent_UDA, na.rm = TRUE))%>% 
    rename(`Band 1` = total_B1, `Band 2` = total_B2, `Band 3` = total_B3, Urgent = total_urgent)

  #change the format of total delivery and separate dcp and then get full data ready for plot
  dcp_summary_longer <- dcp_summary %>% 
    pivot_longer(cols = starts_with("total"),
                 names_to = "Bands",
                 names_prefix = "dcp",
                 values_to = "numbers",
                 values_drop_na = TRUE) 
  
  delivery_total_longer <- delivery_total %>% 
    pivot_longer(cols = starts_with("total"),
                 names_to = "Bands",
                 names_prefix = "dcp",
                 values_to = "all_numbers",
                 values_drop_na = TRUE)
  
  all_lookup <- left_join(dcp_summary_longer, delivery_total_longer, 
                          by = c("month", "Bands", "Region")) %>% 
    select (month, DCP_description.x, Bands, numbers, DCP_description.y, all_numbers)
  
  #calculate the percentage of each dcp description/total delivery 
  total <- all_lookup %>% 
    mutate(assisted_percent = formattable::percent (numbers / all_numbers, digits=2))
  
  if(UDA_or_FP17 == "UDA"){
    
    #UDA is only for those with 'band'
    filtered_data_UDA = filter(total, Bands %in% c("Band 1",	"Band 2",	"Band 3", "Urgent")) %>%
      select(month, "DCP_description.x", "Bands", "assisted_percent") %>%
      rename (DCP_description = DCP_description.x) %>%
      mutate(month = as.Date(month)) %>%
      mutate(DCP_description = str_replace_all(DCP_description, "_", " "))
    
    max_month <- max(filtered_data_UDA$month)
    
    data_labels <- filtered_data_UDA %>% 
      filter(month == max_month)


    UDA_plot <- ggplot(filtered_data_UDA,
                       aes(x=month, y= assisted_percent)) +
      facet_grid(cols = vars(DCP_description)) +
      geom_line(aes(colour = Bands),
                size = 1) +
      geom_text_repel(aes(label = assisted_percent), 
                      data = data_labels, 
                      colour = "black", 
                      position = "dodge") +
      scale_fill_manual(values = c("#009E73", "#F0E442", "#D55E00"),
                        labels = c("Dental Nurse assisted", "Hygienist assisted", "Therapist assisted")) +
      scale_x_date(date_breaks = "1 month",
                   date_labels = "%b-%y") +
      theme_bw() +
      labs(title = "Percentage of total UDAs delivered which had DCP* assistance by DCP roles",
           subtitle = subtitle,
           x = "Month",
           y = "Percentage of total UDAs delivered",
           colour = "Bands",
           caption = "*Dental Care Practitioner") + 
      scale_y_continuous(labels = scales::percent)+
      theme(axis.text.x = element_text(angle = 90, vjust=-0.0001))

    UDA_plot

  }else{
    
    #fp17 is for those with 'total_FP17'
    filtered_data_FP17 <- total %>%
      filter( Bands %in% c("total_FP17")) %>% 
      select("month", "DCP_description.x", "Bands", "assisted_percent") %>%
      mutate(month = as.Date(month)) %>%
      rename ( Percent_of_FP17 = Bands, DCP_description = DCP_description.x) %>%
      mutate(DCP_description = str_replace_all(DCP_description, "_", " ")) 
    
    
    #get the number for the latest month -- used for label in the plot
    latest_month <- max(filtered_data_FP17$month)
    latest_data <- filtered_data_FP17 %>%
    filter(month == latest_month)

    FP17_plot <- ggplot(filtered_data_FP17, 
                        aes(x=month, y= assisted_percent)) +
      geom_line(aes(colour = DCP_description),
                size = 1) +
      geom_text_repel(data = latest_data, aes(label = assisted_percent), 
                    colour = "black", size = 3.5, vjust = -0.25) + 
      theme(legend.position="bottom") +
      theme_bw() +
      scale_x_date(date_breaks = "1 month",
                   date_labels = "%b-%y") +
      labs(title = "Percentage of total Courses of Treatment (CoTs) delivered which had DCP* assistance",
           subtitle = subtitle,
           x = "Month",
           y = "Percentage of total CoTs delivered",
           colour = "DCP description",
           caption = "*Dental Care Practitioner") + 
      scale_y_continuous(labels = scales::percent)  +
      theme(axis.text.x = element_text(angle = 90, vjust=-0.0001))
    
    FP17_plot
    
  }
}

plot_DCP_analysis_ICB_check <- function(data = UDA_calendar_data,
                                        dcp_data = DCP_data,
                                        UDA_or_FP17 = "UDA",
                                        level = "National",
                                        region_STP_name = NULL){
  
  dcp_data <- dcp_data %>%
    rename(month = Month)
  
  #filter for region or STP
  if(level == "Regional"){
    data <- data %>% 
      filter(region_name == region_STP_name)
    
    dcp_data <- dcp_data %>%
      filter(Region == region_STP_name)
    
    subtitle <- region_STP_name 
  }else if(level == "STP"){
    data <- data %>% 
      filter(commissioner_name == region_STP_name)
    
    dcp_data <- dcp_data %>%
      filter(commissioner_name == region_STP_name)
    
    subtitle <- region_STP_name
  }else{
    subtitle <- "England"
  }
  
  colnames(UDA_calendar_data)
  colnames(dcp_data)
  
#calculate total FP19, UDA_B1, B2, B3 and urgent by month for "Total_dentist_only_and_DCP_assisted' by using UDA Calendar data
  delivery_total <-  data %>% 
    rename(Region = region_name) %>%
    group_by(month, commissioner_name) %>%
    dplyr::summarise(total_FP17 = sum(general_FP17s, na.rm = TRUE),
                     total_B1 = sum(UDA_band_1, na.rm = TRUE),
                     total_B2 = sum(UDA_band_2, na.rm = TRUE),
                     total_B3 = sum(UDA_band_3, na.rm = TRUE),
                     total_urgent = sum(UDA_urgent, na.rm = TRUE)) %>%
    mutate(DCP_description = "Total_dentist_only_and_DCP_assisted") %>%
    select(month, commissioner_name, DCP_description, total_FP17,total_B1, total_B2, total_B3, total_urgent)
  
  #calculate total FP19, UDA_B1, B2, B3 and urgent by month for separate DCP description by using DCP data
  dcp_main_new <- dcp_data %>% 
    filter(DCP_description != 'Clinical Technician') %>%
    filter(DCP_description != 'Technician') %>%
    mutate(DCP_description = replace(DCP_description, DCP_description== "Nurse", "Dental_Nurse_assisted"), 
           DCP_description = replace(DCP_description, DCP_description=="Dental Hygienist", "Hygienist_assisted"), 
           DCP_description = replace(DCP_description, DCP_description=="Dental Therapist", "Therapist_assisted"),
           DCP_description = replace(DCP_description, DCP_description=="Hygienist", "Hygienist_assisted"), 
           DCP_description = replace(DCP_description, DCP_description=="Therapist", "Therapist_assisted"))
  
  dcp_summary <- dcp_main_new %>%
    group_by(month, commissioner_name, DCP_description) %>%
    summarise(total_FP17 = sum(FP17_Current_Year_total, na.rm = TRUE),
              total_B1 = sum(Band_1._UDA, na.rm = TRUE),
              total_B2 = sum(Band_2._UDA, na.rm = TRUE),
              total_B3 = sum(Band_3._UDA, na.rm = TRUE),
              total_urgent = sum(Urgent_UDA, na.rm = TRUE)) %>% 
    rename(`Band 1` = total_B1, `Band 2` = total_B2, `Band 3` = total_B3, Urgent = total_urgent)

  #change the format of total delivery and separate dcp and then get full data ready for plotting
  dcp_summary_longer <- dcp_summary %>% 
    pivot_longer(cols = starts_with("total"),
                 names_to = "Bands",
                 names_prefix = "dcp",
                 values_to = "numbers",
                 values_drop_na = TRUE)
  
  delivery_total_longer <- delivery_total %>% 
    pivot_longer(cols = starts_with("total"),
                 names_to = "Bands",
                 names_prefix = "dcp",
                 values_to = "all_numbers",
                 values_drop_na = TRUE)
  
  all_lookup <- left_join(dcp_summary_longer, delivery_total_longer, 
                          by = c("month", "Bands", "commissioner_name")) %>% 
    select(month, DCP_description.x, Bands, numbers, DCP_description.y, all_numbers)
  
   #calculate the percentage of each dcp description/total delivery 
  total <- all_lookup %>% 
    mutate (assisted_percent = formattable::percent (numbers / all_numbers, digits=2))
  
  if(UDA_or_FP17 == "UDA"){
    #UDA is only for those with 'band'
    filtered_data_UDA = filter(total, Bands %in% c("Band 1",	"Band 2",	"Band 3", "Urgent")) %>%
      select(month, "DCP_description.x", "Bands", "assisted_percent") %>%
      rename(DCP_description = DCP_description.x) %>%
      mutate(month = as.Date(month)) %>%
      mutate(DCP_description = str_replace_all(DCP_description, "_", " "))
    
    max_month <- max(filtered_data_UDA$month)
    
    data_labels <- filtered_data_UDA %>% 
      filter(month == max_month)

    UDA_plot <- ggplot(filtered_data_UDA,
                       aes(x=month, y= assisted_percent)) +
      facet_grid(cols = vars(DCP_description)) +
      geom_line(aes(colour = Bands),
                size = 1) +
      geom_text_repel(aes(label = assisted_percent), 
                      data = data_labels, 
                      colour = "black", 
                      position = "dodge") +
      scale_fill_manual(values = c("#009E73", "#F0E442", "#D55E00"),
                        labels = c("Dental Nurse assisted", "Hygienist assisted", "Therapist assisted")) +
      scale_x_date(date_breaks = "1 month",
                   date_labels = "%b-%y") +
      theme_bw() +
      labs(title = "Percentage of total UDAs delivered which had DCP* assistance by DCP roles",
           subtitle = subtitle,
           x = "Month",
           y = "Percentage of total UDAs delivered",
           colour = "Bands",
           caption = "*Dental Care Practitioner") + 
      scale_y_continuous(labels = scales::percent)+
      theme(axis.text.x = element_text(angle = 90, vjust=-0.0001))

    UDA_plot

  }else{
    #fp17 is for those with 'total_FP17'
    filtered_data_FP17 <- total %>%
      filter(Bands %in% c("total_FP17")) %>% 
      select("month", "DCP_description.x", "Bands", "assisted_percent") %>%
      mutate(month = as.Date(month)) %>%
      rename(Percent_of_FP17 = Bands, DCP_description = DCP_description.x) %>%
      mutate(DCP_description = str_replace_all(DCP_description, "_", " ")) 
    
    #get the number for the latest month -- used for label in the plot
    latest_month <- max(filtered_data_FP17$month)
    latest_data <- filtered_data_FP17 %>%
    filter(month == latest_month)

    FP17_plot <- ggplot(filtered_data_FP17, 
                        aes(x=month, y= assisted_percent)) +
      geom_line(aes(colour = DCP_description),
                size = 1) +
      geom_text_repel(data = latest_data, aes(label = assisted_percent), 
                    colour = "black", size = 3.5, vjust = -0.25) + 
      theme(legend.position="bottom") +
      theme_bw() +
      scale_x_date(date_breaks = "1 month",
                   date_labels = "%b-%y") +
      labs(title = "Percentage of total Courses of Treatment (CoTs) delivered which had DCP* assistance",
           subtitle = subtitle,
           x = "Month",
           y = "Percentage of total CoTs delivered",
           colour = "DCP description",
           caption = "*Dental Care Practitioner") + 
      scale_y_continuous(labels = scales::percent)  +
      theme(axis.text.x = element_text(angle = 90, vjust=-0.0001))
    
    FP17_plot

    
  }
}
```

```{r DCP plot by band}
plot_DCP_analysis_band <- function(data = UDA_calendar_data,
                                   dcp_data = DCP_data,
                                   UDA_or_FP17 = "UDA",
                                   level = "National",
                                   region_STP_name = NULL){

  dcp_data <- dcp_data %>%
    rename(month = Month)

  #filter for region or STP
  if(level == "Regional"){
    data <- data %>% 
      filter(region_name == region_STP_name )

    dcp_data <- dcp_data %>%
      filter(Region == region_STP_name)

    subtitle <- region_STP_name 
  }else if(level == "STP"){
    data <- data %>% 
      filter(commissioner_name == region_STP_name)

    dcp_data <- dcp_data %>%
      filter(commissioner_name == region_STP_name)

    subtitle <- region_STP_name
  }else{
    subtitle <- "England"
  }
 #calculate total FP19, UDA_B1, B2, B3 and urgent by month for "Total_dentist_only_and_DCP_assisted' by using UDA Calendar data
  delivery_total <-  data %>% 
    group_by(month) %>%
    dplyr::summarise(total_FP17 = sum(general_FP17s, na.rm = TRUE),
                     total_B1 = sum(UDA_band_1, na.rm = TRUE),
                     total_B2 = sum(UDA_band_2, na.rm = TRUE),
                     total_B3 = sum(UDA_band_3, na.rm = TRUE),
                     total_urgent = sum(UDA_urgent, na.rm = TRUE)) %>%
    mutate(DCP_description = "Total_dentist_only_and_DCP_assisted") %>%
    select(month, DCP_description, total_FP17,total_B1, total_B2, total_B3, total_urgent)

#calculate total FP19, UDA_B1, B2, B3 and urgent by month for separate DCP description by using DCP data
  dcp_main_new <- dcp_data %>% 
    filter(DCP_description != 'Clinical Technician') %>%
    filter(DCP_description != 'Technician') %>%
    mutate(DCP_description = replace(DCP_description, DCP_description== "Nurse", "Dental_Nurse_assisted"), 
           DCP_description = replace(DCP_description, DCP_description=="Dental Hygienist", "Hygienist_assisted"), 
           DCP_description = replace(DCP_description, DCP_description=="Dental Therapist", "Therapist_assisted"),
           DCP_description = replace(DCP_description, DCP_description=="Hygienist", "Hygienist_assisted"), 
           DCP_description = replace(DCP_description, DCP_description=="Therapist", "Therapist_assisted"))


  dcp_summary <- dcp_main_new %>%
    group_by(month, DCP_description) %>%
    summarise(total_FP17 = sum(FP17_Current_Year_total, na.rm = TRUE),
              total_B1 = sum(Band_1._UDA, na.rm = TRUE),
              total_B2 = sum(Band_2._UDA, na.rm = TRUE),
              total_B3 = sum(Band_3._UDA, na.rm = TRUE),
              total_urgent = sum(Urgent_UDA, na.rm = TRUE))

  #change the format of total delivery and separate dcp and then get full data ready for plotting
  dcp_summary_longer <- dcp_summary %>%
    pivot_longer(cols = starts_with("total"),
                 names_to = "Bands",
                 names_prefix = "dcp",
                 values_to = "numbers",
                 values_drop_na = TRUE) 

  delivery_total_longer <- delivery_total %>% 
    pivot_longer(cols = starts_with("total"),
                 names_to = "Bands",
                 names_prefix = "dcp",
                 values_to = "all_numbers",
                 values_drop_na = TRUE)

  all_lookup <- left_join(dcp_summary_longer, delivery_total_longer, 
                          by = c("month", "Bands"))
                          
  #calculate the percentage of each dcp description/total delivery 
  total <- all_lookup %>% 
    mutate(assisted_percent = formattable::percent (numbers / all_numbers, digits=2),
           Bands = replace(Bands, Bands=="total_B1", "UDA Band 1"),
           Bands = replace(Bands, Bands=="total_B2", "UDA Band 2"),
           Bands = replace(Bands, Bands=="total_B3", "UDA Band 3"),
           Bands = replace(Bands, Bands=="total_urgent", "UDA Urgent"))

  if(UDA_or_FP17 == "UDA"){
   #UDA is only for those with 'band'
    filtered_data_UDA = filter(total, Bands %in% c("UDA Band 1",	"UDA Band 2",	"UDA Band 3", "UDA Urgent")) %>%
      select(month, "DCP_description.x", "Bands", "assisted_percent") %>%
      rename(DCP_description = DCP_description.x) %>%
      mutate(month = as.Date(month)) %>%
      mutate(DCP_description = str_replace_all(DCP_description, "_", " "))
    
    max_month <- max(filtered_data_UDA$month)
    
    data_labels <- filtered_data_UDA %>% 
      filter(month == max_month)

    UDA_plot <- ggplot(filtered_data_UDA,
                       aes(x=month, y= assisted_percent)) +
      facet_grid(cols = vars(DCP_description)) +
      geom_line(aes(colour = Bands),
                size = 1) +
      geom_text_repel(aes(label = assisted_percent), 
                      data = data_labels, 
                      colour = "black", 
                      position = "dodge") +
      scale_fill_manual(values = c("#009E73", "#F0E442", "#D55E00"),
                        labels = c("Dental Nurse assisted", "Hygienist assisted", "Therapist assisted")) +
      scale_x_date(date_breaks = "1 month",
                   date_labels = "%b-%y") +
      theme_bw() +
      labs(title = "Percentage of total UDAs delivered which had Dental Care Practitioner (DCP) assistance by DCP roles",
           subtitle = subtitle,
           x = "Month",
           y = "Percentage of total UDAs delivered",
           colour = "Bands",
           caption = "Contracts included: GDS/PDS/PDS+ where Total contracted UDA>100.
The most recent two months data will be incomplete and subject to change, particularly for the most recent month. We expect final data to be higher") + 
      scale_y_continuous(labels = scales::percent)+
      theme(axis.text.x = element_text(angle = 90, vjust=-0.0001))

    UDA_plot


  }else{
#UDA is only for those with 'total_FP17'
    filtered_data_FP17 <- total %>%
      filter( Bands %in% c("total_FP17")) %>% 
      select("month", "DCP_description.x", "Bands", "assisted_percent") %>%
      mutate(month = as.Date(month)) %>%
      rename ( Percent_of_FP17 = Bands, DCP_description = DCP_description.x) %>%
      mutate(DCP_description = str_replace_all(DCP_description, "_", " ")) 


    FP17_plot <- ggplot(filtered_data_FP17,
                        aes(x=month, y= assisted_percent)) +
      geom_line(aes(colour = DCP_description),
                size = 1) +
      geom_text(aes(label = assisted_percent),
                colour = "black", size= 3.5, vjust=-0.25) +
      theme(legend.position="bottom") +
      theme_bw() +
      scale_x_date(date_breaks = "1 month",
                   date_labels = "%b-%y") +
      labs(title = "Percentage of total Courses of Treatment (CoTs) delivered which had DCP* assistance",
           subtitle = subtitle,
           x = "Month",
           y = "Percentage of total CoTs delivered",
           colour = "DCP description",
           caption = "Contracts included: GDS/PDS/PDS+ where Total contracted UDA>100.
The most recent two months data will be incomplete and subject to change, particularly for the most recent month. We expect final data to be higher") + 
      scale_y_continuous(labels = scales::percent)  +
      theme(axis.text.x = element_text(angle = 90, vjust=-0.0001))

    FP17_plot


  }
}
```

