---
title: "SQL pulls for SMT Dental Pack"
---
```{r}
library(tidyverse)
library(readxl)
library(DBI)
library(odbc)
library(downloadthis)
library(lubridate)
```

```{r working days}

#read local file -- No working days in each month
working_days <- read_excel("N:/_Everyone/Primary Care Group/SMT_Dental DENT 2022_23-008/workdays.xlsx",sheet = "workdays")
working_days$month<- as.Date(working_days$Month)

```

```{r contractors}

#extract contractual_dataset from NCDR
pull_contractual_dataset <- function(){
  
  con <- dbConnect(odbc::odbc(), "NCDR")
  
  sql <- "SELECT [YEAR_MONTH],
                [CONTRACT_NUMBER]
  FROM [NHSE_Sandbox_PrimaryCareNHSContracts].[Dental].[Calendar_Contracts]"
  result <- dbSendQuery(con, sql)
  contractual_dataset <- dbFetch(result)
  dbClearResult(result)
  
  contractual_dataset
}

#remove duplicates
contractual_dataset<-pull_contractual_dataset()%>%
    mutate(YEAR_MONTH = as.Date(YEAR_MONTH))%>% 
  group_by(YEAR_MONTH) %>% summarize(CONTRACT_NUMBER = unique(CONTRACT_NUMBER))


```



```{r UDA}

#extract UDA calendar data
pull_UDA_calendar_data <- function(){
  
  con <- dbConnect(odbc::odbc(), "NCDR")
  
  sql <- "SELECT *
  FROM [NHSE_Sandbox_PrimaryCareNHSContracts].[Dental].[Calendar_UDA_Activity] a
  LEFT JOIN (SELECT DISTINCT
			[Region_Name]
			,[STP_Code]
			FROM [NHSE_Reference].[dbo].[tbl_Ref_ODS_Commissioner_Hierarchies]
			WHERE STP_Code NOT IN ('DUM001', 'DUM002', 'UNK','X24')) b
		ON a.[COMMISSIONER_CODE] = b.[STP_Code]"
  result <- dbSendQuery(con, sql)
  UDA_calendar_data <- dbFetch(result)
  dbClearResult(result)
  
  UDA_calendar_data
}

#only include contractors in contractual_dataset
UDA_calendar_data<-pull_UDA_calendar_data()%>%
  inner_join(contractual_dataset,by=c('YEAR_MONTH','CONTRACT_NUMBER'))
#exclude those with UDA target less than 1 - rename fields
UDA_calendar_data = dplyr::filter(UDA_calendar_data, as.numeric(UDA_PERF_TARGET) > 100)
names(UDA_calendar_data) <- base::tolower(names(UDA_calendar_data))
UDA_calendar_data<-UDA_calendar_data%>%
  rename(month=year_month,annual_contracted_UDA=uda_perf_target,UDA_delivered=uda_delivered,commissioner_ods_code_icb=commissioner_code,name_or_company_name=provider_name,general_FP17s=late_submitted_fp17,FP17s_band_1=band_1_delivered,FP17s_band_2=band_2_delivered,FP17s_band_2a=band_2a_delivered,FP17s_band_2b=band_2b_delivered,FP17s_band_2c=band_2c_delivered,FP17s_band_3=band_3_delivered,FP17s_band_urgent=band_urgent_delivered,FP17s_band_other=band_other_delivered,UDA_band_1=uda_band_1_delivered,UDA_band_2=uda_band_2_delivered,UDA_band_3=uda_band_3_delivered,UDA_urgent=uda_band_urgent_delivered,UDA_other=uda_band_other_delivered) %>% 
  rowwise() %>% 
  mutate(FP17s_band_2 = sum(FP17s_band_2, FP17s_band_2a, FP17s_band_2b, FP17s_band_2c, na.rm = T))

UDA_calendar_data$region_name<- str_to_title(UDA_calendar_data$region_name)

UDA_calendar_data$commissioner_name<- str_to_title(UDA_calendar_data$commissioner_name)
UDA_calendar_data$commissioner_name = substr(UDA_calendar_data$commissioner_name,1,nchar(UDA_calendar_data$commissioner_name)-3)
UDA_calendar_data$commissioner_name<- paste0(UDA_calendar_data$commissioner_name, rep("ICB", nrow(UDA_calendar_data)))

```



```{r UDA WITH FD}

#extract UDA calendar data
pull_UDA_calendar_data_FD_only <- function(){
  
  con <- dbConnect(odbc::odbc(), "NCDR")
  
  sql <- "SELECT *
  FROM [NHSE_Sandbox_PrimaryCareNHSContracts].[Dental].[Calendar_UDA_Activity_FD_only] a
  LEFT JOIN (SELECT DISTINCT
			[Region_Name]
			,[STP_Code]
			FROM [NHSE_Reference].[dbo].[tbl_Ref_ODS_Commissioner_Hierarchies]
			WHERE STP_Code NOT IN ('DUM001', 'DUM002', 'UNK','X24')) b
		ON a.[COMMISSIONER_CODE] = b.[STP_Code]"
  result <- dbSendQuery(con, sql)
  pull_UDA_calendar_data_FD_only <- dbFetch(result)
  dbClearResult(result)
  
  pull_UDA_calendar_data_FD_only
}

#only include contractors in contractual_dataset
UDA_calendar_data_FD_only<-pull_UDA_calendar_data_FD_only()%>%
  inner_join(contractual_dataset,by=c('YEAR_MONTH','CONTRACT_NUMBER'))
#exclude those with UDA target less than 1 - rename fields
UDA_calendar_data_FD_only = dplyr::filter(UDA_calendar_data_FD_only, as.numeric(UDA_PERF_TARGET) > 100)
names(UDA_calendar_data_FD_only) <- base::tolower(names(UDA_calendar_data_FD_only))
UDA_calendar_data_FD_only<-UDA_calendar_data_FD_only%>%
  rename(month=year_month,annual_contracted_UDA=uda_perf_target,UDA_delivered=uda_delivered,commissioner_ods_code_icb=commissioner_code,name_or_company_name=provider_name,FP17s_band_1=band_1_delivered,FP17s_band_2=band_2_delivered,FP17s_band_2a=band_2a_delivered,FP17s_band_2b=band_2b_delivered,FP17s_band_2c=band_2c_delivered,FP17s_band_3=band_3_delivered,FP17s_band_urgent=band_urgent_delivered,FP17s_band_other=band_other_delivered,UDA_band_1=uda_band_1_delivered,UDA_band_2=uda_band_2_delivered,UDA_band_3=uda_band_3_delivered,UDA_urgent=uda_band_urgent_delivered,UDA_other=uda_band_other_delivered) %>% 
  rowwise() %>% 
  mutate(FP17s_band_2 = sum(FP17s_band_2, FP17s_band_2a, FP17s_band_2b, FP17s_band_2c, na.rm = T),
         general_FP17s=sum(FP17s_band_2, FP17s_band_1, FP17s_band_3, FP17s_band_urgent,FP17s_band_other, na.rm = T)) 

UDA_calendar_data_FD_only$region_name<- str_to_title(UDA_calendar_data_FD_only$region_name)
UDA_calendar_data_FD_only$commissioner_name<- str_to_title(UDA_calendar_data_FD_only$commissioner_name)
UDA_calendar_data_FD_only$commissioner_name = substr(UDA_calendar_data_FD_only$commissioner_name,1,nchar(UDA_calendar_data_FD_only$commissioner_name)-3)
UDA_calendar_data_FD_only$commissioner_name<- paste0(UDA_calendar_data_FD_only$commissioner_name, rep("ICB", nrow(UDA_calendar_data_FD_only)))
UDA_calendar_data_FD_only<-UDA_calendar_data_FD_only %>%
  select("month","commissioner_ods_code_icb" ,"commissioner_name","contract_number","child_12m_count" ,"adult_24m_count" ,  'general_FP17s',        "FP17s_band_1","FP17s_band_2","FP17s_band_2a","FP17s_band_2b","FP17s_band_2c","FP17s_band_3","FP17s_band_urgent","FP17s_band_other","UDA_delivered","UDA_band_1","UDA_band_2", "uda_band_2a_delivered","uda_band_2b_delivered","uda_band_2c_delivered","UDA_band_3","UDA_urgent","UDA_other")

UDA_calendar_data_FD <- UDA_calendar_data%>%
  left_join(UDA_calendar_data_FD_only, by=c("month","commissioner_ods_code_icb","commissioner_name","contract_number" ))%>%
  mutate(UDA_delivered=sum(UDA_delivered.x, UDA_delivered.y, na.rm = TRUE),
         general_FP17s=sum(general_FP17s.x, general_FP17s.y, na.rm = TRUE),
         FP17s_band_1=sum(FP17s_band_1.x, FP17s_band_1.y, na.rm = TRUE),
         FP17s_band_2=sum(FP17s_band_2.x, FP17s_band_2.y, na.rm = TRUE),
         FP17s_band_3=sum(FP17s_band_3.x, FP17s_band_3.y, na.rm = TRUE),
         FP17s_band_urgent=sum(FP17s_band_urgent.x, FP17s_band_urgent.y, na.rm = TRUE),
         FP17s_band_other=sum(FP17s_band_other.x,FP17s_band_other.y, na.rm = TRUE),
         child_12m_count=sum(child_12m_count.x,child_12m_count.y, na.rm = TRUE),
         adult_24m_count=sum(adult_24m_count.x, adult_24m_count.y, na.rm = TRUE),
        FP17s_band_2a=sum(FP17s_band_2a.x, FP17s_band_2a.y, na.rm = TRUE),
        FP17s_band_2b=sum(FP17s_band_2b.x, FP17s_band_2b.y, na.rm = TRUE),
        FP17s_band_2c=sum(FP17s_band_2c.x, FP17s_band_2c.y, na.rm = TRUE),
        UDA_band_1=sum(UDA_band_1.x, UDA_band_1.y, na.rm = TRUE),
        UDA_band_2=sum(UDA_band_2.x, UDA_band_2.y, na.rm = TRUE),
        uda_band_2a_delivered=sum(uda_band_2a_delivered.x, uda_band_2a_delivered.y, na.rm = TRUE),
        uda_band_2b_delivered=sum(uda_band_2b_delivered.x, uda_band_2b_delivered.y, na.rm = TRUE),
        uda_band_2c_delivered=sum(uda_band_2c_delivered.x, uda_band_2c_delivered.y, na.rm = TRUE),
        UDA_band_3=sum(UDA_band_3.x, UDA_band_3.y, na.rm = TRUE),
        UDA_band_3=sum(UDA_band_3.x, UDA_band_3.y, na.rm = TRUE),
        UDA_urgent=sum(UDA_urgent.x, UDA_urgent.y, na.rm = TRUE),
        UDA_other=sum(UDA_other.x, UDA_other.y, na.rm = TRUE))

```


```{r UOA}

# pull_UOA_calendar_data <- function(){
#   
#   con <- dbConnect(odbc::odbc(), "NCDR")
#   
#   sql <- "SELECT *
#   FROM [NHSE_Sandbox_PrimaryCareNHSContracts].[Dental].[orthodontic_activity]
#   where [Year_Month] > '2016-03-01'"
#   result <- dbSendQuery(con, sql)
#   UOA_calendar_data <- dbFetch(result)
#   dbClearResult(result)
#   
#   UOA_calendar_data
# }
# 
# UOA_calendar_data<-pull_UOA_calendar_data()
# #only include contractors in contractual_dataset and exclude those with UOA target less than 1 - rename fields
# UOA_calendar_data = dplyr::filter(UOA_calendar_data, as.numeric(UOA_PERF_TAR) > 100)
# UOA_calendar_data<-UOA_calendar_data%>%
#   inner_join(contractual_dataset,by=c('YEAR_MONTH','CONTRACT_NUMBER'))
# names(UOA_calendar_data) <- base::tolower(names(UOA_calendar_data))
# UOA_calendar_data<-UOA_calendar_data%>%
#   rename(month=year_month,commissioner_ods_code_icb=commissioner_code,name_or_company_name=provider_name,annual_contracted_UOA=uoa_perf_tar,UOA_delivered=uoa_delivered,orthodontic_starts=ortho_trt_started,orthodontic_completions=ortho_trt_completed)
# 
# UOA_calendar_data$region_name<- str_to_title(UOA_calendar_data$region_name)
# UOA_calendar_data$commissioner_name<- str_to_title(UOA_calendar_data$commissioner_name)
# UOA_calendar_data$commissioner_name = substr(UOA_calendar_data$commissioner_name,1,nchar(UOA_calendar_data$commissioner_name)-3)
# UOA_calendar_data$commissioner_name<- paste0(UOA_calendar_data$commissioner_name, rep("ICB", nrow(UOA_calendar_data)))

```


```{r unique patients}
pull_unique_patients <- function(){
  con <- dbConnect(odbc::odbc(), "NCDR")
  
  sql <- "SELECT *
  FROM [NHSE_Sandbox_PrimaryCareNHSContracts].[Dental].[Calendar_Unique_rolling] a
  LEFT JOIN (SELECT DISTINCT
			[Region_Name]
			,[STP_Code]
			FROM [NHSE_Reference].[dbo].[tbl_Ref_ODS_Commissioner_Hierarchies]
			WHERE STP_Code NOT IN ('DUM001', 'DUM002', 'UNK','X24')) b
		ON a.[COMMISSIONER_CODE] = b.[STP_Code]"
  result <- dbSendQuery(con, sql)
  unique_patients_rolling <- dbFetch(result)
  dbClearResult(result)
  
  unique_patients_rolling
  
  names(unique_patients_rolling) <- base::tolower(names(unique_patients_rolling))
  
  unique_patients_rolling <- unique_patients_rolling %>% 
    rename(month=year_month,commissioner_ods_code_icb=commissioner_code)
}
```



```{r dental 111 data}
#get dental 111 data from local file
dental_data_111 <- read_excel("N:/_Everyone/Primary Care Group/SMT_Dental DENT 2022_23-008/111_pathways_data/dental_data_111.xlsx")
```


```{r  DCP}

#extract DCP data
pull_dcp_data <- function(){
  
  con <- dbConnect(odbc::odbc(), "NCDR")
  
  sql <- "SELECT *
  FROM [NHSE_Sandbox_PrimaryCareNHSContracts].[Dental].[Calendar_DCP] a
  LEFT JOIN (SELECT DISTINCT
			[Region_Name]
			,[STP_Code]
			FROM [NHSE_Reference].[dbo].[tbl_Ref_ODS_Commissioner_Hierarchies]
			WHERE STP_Code NOT IN ('DUM001', 'DUM002', 'UNK','X24')) b
		ON a.[COMMISSIONER_CODE] = b.[STP_Code]"
  result <- dbSendQuery(con, sql)
  DCP_data <- dbFetch(result)
  dbClearResult(result)
  
  DCP_data
}

DCP_data<-pull_dcp_data()%>%
  inner_join(contractual_dataset,by=c('YEAR_MONTH','CONTRACT_NUMBER'))

#exclude those with UDA target less than 100 - rename fields
contractors=UDA_calendar_data%>%
  select(month,contract_number)
DCP_data = DCP_data%>%
  inner_join(contractors,by=c('YEAR_MONTH'='month','CONTRACT_NUMBER'='contract_number'))%>%
  filter(!is.na(DCP_DESC)&DCP_DESC!="")

DCP_data <- DCP_data %>%
    dplyr::rename(Month=YEAR_MONTH,
      Contract_Number = `CONTRACT_NUMBER`,
           Contract.Type = `CONTRACT_TYPE`, 
           commissioner_name = `COMMISSIONER_NAME`,   
           DCP_description = `DCP_DESC`,
           UDA_Delivered_Current_Year =  `UDA_DELIVERED`,               
           FP17_Current_Year_total = `LATE_SUBMITTED_FP17`, 
           Band_1._UDA = `UDA_BAND_1_DELIVERED`,          
           Band_2._UDA = `UDA_BAND_2_DELIVERED` ,        
           Band_3._UDA = `UDA_BAND_3_DELIVERED`,
           Urgent_UDA = `UDA_BAND_URGENT_DELIVERED`,
           other_UDA = `UDA_BAND_OTHER_DELIVERED`, 
           FP17_Current_Year_B1= `BAND_1_DELIVERED`,       
           FP17_Current_Year_B2 = `BAND_2_DELIVERED`,       
           FP17_Current_Year_B3 = `BAND_3_DELIVERED`,       
           FP17_Current_Year_urgent = `BAND_URGENT_DELIVERED`,
           FP17_Current_Year_other= `BAND_OTHER_DELIVERED`)

#DCP_data$region_name<- str_to_title(DCP_data$region_name)

DCP_data$commissioner_name<- str_to_title(DCP_data$commissioner_name)
DCP_data$commissioner_name = substr(DCP_data$commissioner_name,1,nchar(DCP_data$commissioner_name)-3)
DCP_data$commissioner_name<- paste0(DCP_data$commissioner_name, rep("ICB", nrow(DCP_data)))


```
